Repository questdb/questdb, pull requests merged in 2021-11, with the labels that each got.

#1512 fix(sql): fix union all with all literals
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/griffin/UnionTest.java
Labels: Bug, SQL

#1509 chore(ui): virtual renderer for the table schema pane
  ui/package-lock.json
  ui/package.json
  ui/src/components/VirtualList/index.tsx
  ui/src/components/index.ts
  ui/src/scenes/Schema/Table/index.tsx
  ui/src/scenes/Schema/index.tsx
Labels: UI

#1506 feat(sql): add strpos() function
  benchmarks/src/main/java/org/questdb/StrLoopBenchmark.java
  benchmarks/src/main/java/org/questdb/StrPosBenchmark.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactory.java
  core/src/main/java/io/questdb/std/str/StringSink.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactoryTest.java
Labels: Enhancement, SQL, Java

#1535 chore(sql): improve strpos function
  benchmarks/src/main/java/org/questdb/StrPosBenchmark.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactory.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactoryTest.java
Labels: SQL, Performance, Java

#1542 fix(cairo): fix mmap offset page alignment in o3
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/test/java/io/questdb/griffin/O3CommitLagTest.java
  core/src/test/java/io/questdb/griffin/O3Test.java
Labels: Bug, Cairo

#1526 feat(sql): ceil() and floor() functions
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilFloatFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/FloorDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/FloorFloatFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilFloatFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/FloorDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/FloorFloatFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/FloorFunctionFactoryTest.java
Labels: Enhancement, SQL, Java

#1550 fix(sql): treat zero char as empty string literal
  core/src/main/java/io/questdb/griffin/FunctionParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfIFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/StrConstant.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/cast/CastTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/conditional/NullIfFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/eq/NullIfCharCharFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/LengthFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/LengthSymbolVFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactoryTest.java
Labels: Enhancement, SQL

#1555 feat(sql): support count(1) syntax
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/groupby/CountTest.java
Labels: New feature, SQL

#1558 chore(test): remove testOneToParallelSubscriber test
  core/src/test/java/io/questdb/mp/ConcurrentTest.java
Labels: Flaky test

#1564 chore(ui): fix keyboard shortcuts
  ui/src/scenes/Editor/Ace/index.tsx
Labels: UI

#1566 chore(ui): fix shrunk notifications
  ui/src/scenes/Notifications/Notification/ErrorNotification/index.tsx
  ui/src/scenes/Notifications/Notification/SuccessNotification/index.tsx
  ui/src/scenes/Notifications/Notification/styles.tsx
Labels: UI

#1576 fix(cairo): fix table locked on concurrent reads and create table
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/EmbeddedApiTest.java
Labels: Bug, Cairo, Embedded API

#1586 fix(sql): NPE in latest by with symbol filter
  core/src/main/java/io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Labels: Bug, SQL

#1597 chore(ilp): update prop names and values in config files
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/resources/io/questdb/cutlass/line/tcp/LineTcpO3Test.server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Cairo, Documentation

#1587 chore(ui): fix create table schema
  ui/src/scenes/Schema/Table/ContextualMenu/services.ts
Labels: Bug, UI

#1621 feat(ui): add column type to grid
  ui/src/js/console/grid.js
  ui/src/styles/_grid.scss
Labels: Enhancement, UI

#1605 fix(ilp): sanitize table name to avoid FS corruption
  benchmarks/src/main/java/org/questdb/LineTCPSenderMain.java
  benchmarks/src/main/java/org/questdb/RawTCPILPSenderMain.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java
  core/src/main/java/io/questdb/std/str/DirectByteCharSequence.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParser2Test.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParserTest.java
Labels: Bug

#1610 feat(ui): change sql editor to monaco - vscode core
  ui/.eslintrc.js
  ui/.nvmrc
  ui/package-lock.json
  ui/package.json
  ui/src/components/Splitter/index.tsx
  ui/src/consts/index.ts
  ui/src/providers/EditorProvider/index.tsx
  ui/src/providers/index.tsx
  ui/src/scenes/Editor/Ace/index.tsx
  ui/src/scenes/Editor/Ace/questdbMode.ts
  ui/src/scenes/Editor/Ace/utils.ts
  ui/src/scenes/Editor/Monaco/dracula.ts
  ui/src/scenes/Editor/Monaco/index.tsx
  ui/src/scenes/Editor/Monaco/questdb-sql.ts
  ui/src/scenes/Editor/Monaco/usePreferences.ts
  ui/src/scenes/Editor/Monaco/utils.ts
  ui/src/scenes/Editor/QueryPicker/index.tsx
  ui/src/scenes/Editor/index.tsx
  ui/src/scenes/Layout/index.tsx
  ui/src/scenes/Schema/Row/index.tsx
  ui/webpack.config.js
Labels: Enhancement, New feature, UI
