Repository questdb/questdb, pull requests merged in 2021-09, with the labels that each got.

#1279 docs: modify tsbs instructions [skip ci]
  artifacts/tsbs/README.md
Labels: Documentation

#1289 review ILP/UDP value parser and fix corner cases
  core/src/main/java/io/questdb/cutlass/line/CairoLineProtoParserSupport.java
  core/src/test/java/io/questdb/cutlass/line/CairoLineProtoParserSupportTest.java
  core/src/test/java/io/questdb/cutlass/line/udp/CairoLineProtoParserTest.java
  core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertOtherTypesTest.java
Labels: ILP

#1325 chore(ui): minor edit to UI footer
  ui/src/scenes/Footer/index.tsx
Labels: UI

#1323 feat(ui): copy table schema to clipboard
  ui/.eslintrc.js
  ui/package-lock.json
  ui/package.json
  ui/src/components/ContextMenu/ContextMenu.tsx
  ui/src/components/ContextMenu/MenuItem.tsx
  ui/src/components/ContextMenu/index.tsx
  ui/src/scenes/Footer/BuildVersion/index.tsx
  ui/src/scenes/Footer/BuildVersion/services.ts
  ui/src/scenes/Schema/Table/ContextualMenu/index.tsx
  ui/src/scenes/Schema/Table/ContextualMenu/services.ts
  ui/src/scenes/Schema/Table/index.tsx
  ui/src/utils/questdb.ts
Labels: UI
