Repository questdb/questdb, pull requests merged in 2022-03, with the labels that each got.

#1924 docs(CONTRIBUTING): remove section about commit squashing
  CONTRIBUTING.md
Labels: Documentation

#1927 feat(UI): support `query` and `executeQuery` URL params for inserting and executing queries in web console
  ui/src/scenes/Editor/Monaco/index.tsx
  ui/src/scenes/Editor/Monaco/utils.ts
  ui/src/utils/fromFetch.ts
Labels: Bug, New feature, UI

#1907 core(cairo): add filesystem snapshot support
  core/src/main/c/share/files.c
  core/src/main/c/windows/files.c
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/TelemetryJob.java
  core/src/main/java/io/questdb/WorkerPoolAwareConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/ColumnVersionReader.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/TableReader.java
  core/src/main/java/io/questdb/cairo/TableReaderMetadata.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TxReader.java
  core/src/main/java/io/questdb/cairo/vm/Vm.java
  core/src/main/java/io/questdb/cutlass/http/HttpServer.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGJobContext.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java
  core/src/main/java/io/questdb/griffin/CompiledQuery.java
  core/src/main/java/io/questdb/griffin/CompiledQueryImpl.java
  core/src/main/java/io/questdb/griffin/DatabaseSnapshotAgent.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/engine/table/TableListRecordCursorFactory.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/FilesFacade.java
  core/src/main/java/io/questdb/std/FilesFacadeImpl.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/osx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/TelemetryTest.java
  core/src/test/java/io/questdb/cairo/AbstractCairoTest.java
  core/src/test/java/io/questdb/cairo/ColumnVersionWriterTest.java
  core/src/test/java/io/questdb/cairo/TableReaderMetadataTest.java
  core/src/test/java/io/questdb/cutlass/http/HttpHealthCheckTestBuilder.java
  core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java
  core/src/test/java/io/questdb/cutlass/line/udp/LinuxLineUdpProtoReceiverTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/griffin/AbstractGriffinTest.java
  core/src/test/java/io/questdb/griffin/SnapshotTest.java
  core/src/test/java/io/questdb/griffin/SnapshotWindowsTest.java
  core/src/test/java/io/questdb/griffin/TableBackupTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
  core/src/test/resources/server.conf
Labels: Enhancement, SQL, Core

#1932 chore(ui): remove redundant console.log
  ui/src/scenes/Editor/Monaco/utils.ts
Labels: UI

#1941 fix(pgwire): fixed reading boolean fields using PGX and GoLang
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/test/java/io/questdb/cutlass/NetUtils.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
Labels: Compatibility, Tidy up

#1945 chore(conf): add default values for ILP props
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Documentation, Tidy up

#1952 chore(ui): add help button in web console
  ui/src/scenes/Editor/Menu/index.tsx
Labels: Enhancement, UI

#1960 fix(ui): fix copy to clipboard for safari
  ui/src/scenes/Footer/BuildVersion/index.tsx
  ui/src/scenes/Schema/Table/ContextualMenu/index.tsx
  ui/src/utils/copyToClipboard.ts
  ui/src/utils/index.ts
Labels: Bug, UI

#1971 Add geohash support for CSV import and export
  core/src/main/java/io/questdb/cairo/ColumnType.java
  core/src/main/java/io/questdb/cairo/GeoHashes.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/cutlass/text/TextMetadataParser.java
  core/src/main/java/io/questdb/cutlass/text/types/GeoHashAdapter.java
  core/src/main/java/io/questdb/cutlass/text/types/TypeManager.java
  core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/cutlass/http/SendAndReceiveRequestBuilder.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Labels: Bug, REST API

#1965 fix(ui): error highlighting on selections
  ui/src/scenes/Editor/Monaco/questdb-sql/conf.ts
  ui/src/scenes/Editor/Monaco/utils.ts
Labels: Bug, UI

#1963 fix(ui): fix unresponsive ui on hidden tables
  ui/src/scenes/Editor/Monaco/index.tsx
Labels: Bug, UI

#1985 fix(ui): adjust regex to allow brackets in editor tokens
  ui/src/scenes/Editor/Monaco/questdb-sql/conf.ts
Labels: Bug, UI

#1967 feat(sql): 'is null' is an alias for '= null' and 'is not null' for '!= null'
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/ExpressionParser.java
  core/src/main/java/io/questdb/griffin/SqlKeywords.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/griffin/ExpressionParserTest.java
  core/src/test/java/io/questdb/griffin/InsertNullTest.java
  core/src/test/java/io/questdb/griffin/SqlParserTest.java
Labels: New feature

#1950 feat(sql): parallelize JIT-compiled filters via async offload
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/sql/PageAddressCache.java
  core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/CompiledFilterRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/CompiledFilterRecordCursorFactory.java
  core/src/main/java/io/questdb/log/Logger.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java
  core/src/test/java/io/questdb/griffin/CompiledFilterRegressionTest.java
  core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
Labels: SQL, Performance

#1992 feat(ui): improve "Example Queries" popup to support groups
  ui/src/scenes/Editor/QueryPicker/Row/index.tsx
  ui/src/scenes/Editor/QueryPicker/index.tsx
  ui/src/store/Console/types.ts
Labels: UI

#1993 feat(ui): add red dot indicator on "Example Queries" button
  ui/src/providers/LocalStorageProvider/index.tsx
  ui/src/providers/LocalStorageProvider/types.ts
  ui/src/scenes/Editor/Menu/index.tsx
  ui/src/utils/localStorage/types.ts
Labels: UI
