Repository questdb/questdb, pull requests merged in 2022-10, with the labels that each got.

#2573 test(ilp): fix flapping client TLS tests
  core/src/test/java/io/questdb/test/tools/TlsProxy.java
Labels: Bug, Flaky Test

#2583 chore(core): use madvise with MADV_RANDOM for column files in table writer
  core/src/main/c/linux/files.c
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/WalWriter.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryFMCRImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java
  core/src/main/java/io/questdb/cairo/vm/NullMemoryMR.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryM.java
  core/src/main/java/io/questdb/cairo/vm/api/NullMemory.java
  core/src/main/java/io/questdb/cutlass/text/TextImportTask.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/FilesFacade.java
  core/src/main/java/io/questdb/std/FilesFacadeImpl.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/cairo/vm/ContinuousOffsetMappedMemoryTest.java
Labels: Performance, Core

#2598 fix(sql): fix unexpected NPE thrown in query with analytical function and filter
  core/src/main/java/io/questdb/cairo/RecordChain.java
  core/src/main/java/io/questdb/cairo/TxReader.java
  core/src/main/java/io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/MapSymbolColumn.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/orderby/RecordTreeChain.java
  core/src/main/java/io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/orderby/SortedRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/FilteredRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#2602 fix(sql): fix TableReader metadata open when columns are added frequently
  core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java
  core/src/test/java/io/questdb/griffin/O3FailureTest.java
Labels: Bug, Core

#2592 fix(sql): change default import work dir location to avoid extra file copying
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
  core/src/test/java/io/questdb/griffin/CopyTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Performance, Tidy up

#2597 docs(conf): bogus TTL values in server.conf
  core/src/main/resources/io/questdb/site/conf/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Hacktoberfest

#2582 feat(sql): add `lower()` and `upper()` string functions
  core/src/main/java/io/questdb/griffin/engine/functions/str/LowerFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/UpperFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/LowerFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/UpperFunctionFactoryTest.java
Labels: Enhancement, SQL, Hacktoberfest

#2580 feat(sql): support `create table like` syntax
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/SqlKeywords.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/model/CreateTableModel.java
  core/src/test/java/io/questdb/cairo/CreateTableTest.java
  core/src/test/java/io/questdb/griffin/SqlParserTest.java
Labels: Enhancement, SQL, Hacktoberfest

#2572 fix(sql): fix sampling aligned to calendar timezone and ending with semicolon or followed by order-by/limit
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/griffin/SampleBySqlParserTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#2599 feat(sql): add `position()` alias for `strpos()`
  core/src/main/java/io/questdb/griffin/engine/functions/str/PositionFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/PositionFunctionFactoryTest.java
Labels: Hacktoberfest

#2600 feat(sql): add SQL function ceiling with double and float arguments
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilingDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilingFloatFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilingDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilingFloatFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CeilingFunctionFactoryTest.java
Labels: Hacktoberfest

#2601 chore(core): make use of madvise/fadvise in O3 tasks
  core/src/main/java/io/questdb/cairo/O3CopyJob.java
  core/src/main/java/io/questdb/cairo/O3OpenColumnJob.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
Labels: Performance, Core

#2606 feat(core): Allow ALTER DROP of last partition
  core/src/main/java/io/questdb/cairo/ColumnPurgeOperator.java
  core/src/main/java/io/questdb/cairo/O3PartitionPurgeJob.java
  core/src/main/java/io/questdb/cairo/O3Utils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java
  core/src/main/java/io/questdb/std/Unsafe.java
  core/src/test/java/io/questdb/cairo/TableReaderTest.java
  core/src/test/java/io/questdb/griffin/AlterTableDropActivePartitionTest.java
  core/src/test/java/io/questdb/griffin/AlterTableDropPartitionTest.java
Labels: Enhancement, Core

#2605 fix(sql): rename log() to ln() natural logarithm function
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilingDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/CeilingFloatFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/LnDoubleFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/FunctionParserErrorTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/LnDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/LnFunctionFactoryTest.java
Labels: SQL, Tidy up, Hacktoberfest

#2579 feat(sql): add log10 SQL function to calculate base 10 logarithm of double argument
  core/src/main/java/io/questdb/griffin/engine/functions/math/LogDoubleFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/math/LogDoubleFunctionFactoryTest.java
Labels: New feature, SQL, Hacktoberfest

#2608 feat(sql): implement starts_with str function
  core/src/main/java/io/questdb/griffin/engine/functions/str/StartsWithStrFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/StartsWithStrFunctionFactoryTest.java
Labels: New feature, SQL, Hacktoberfest

#2633 chore(core): mark sql append page size prop as obsolete
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
Labels: Tidy up

#2627 fix(core): fix commit error when many partitions are added and merged in one transaction
  benchmarks/src/main/java/org/questdb/ArrayFillBenchmark.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/O3CopyJob.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java
  core/src/test/java/io/questdb/griffin/AbstractO3Test.java
  core/src/test/java/io/questdb/griffin/O3Test.java
Labels: Bug, Core

#2624 feat(sql) support of rank() function
  core/src/main/java/io/questdb/cairo/RecordChain.java
  core/src/main/java/io/questdb/cairo/sql/AnalyticSPI.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/analytic/AnalyticFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/analytic/RankFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Labels: New feature, SQL, Hacktoberfest

#2642 chore(sql): unify pre-touch mechanisms between parallel filters and touch function
  core/src/main/java/io/questdb/griffin/engine/functions/table/TouchTableFunctionFactory.java
  core/src/test/java/io/questdb/griffin/engine/functions/TouchTableFunctionTest.java
Labels: SQL, Tidy up

#2652 fix(sql): spurious duplicate column name errors in joins
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/test/java/io/questdb/griffin/AsOfJoinTest.java
Labels: Bug

#2654 fix(ilp): fix variability in ILP performance
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpUtils.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/main/java/io/questdb/std/DirectByteCharSequenceIntHashMap.java
  core/src/test/java/io/questdb/std/CharSequenceIntHashMapTest.java
  core/src/test/java/io/questdb/std/DirectByteCharSequenceIntHashMapTest.java
Labels: Performance, ILP

#2656 feat(sql): Support row_number() over() and row_number() over(order by)
  core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Labels: Enhancement, SQL, Hacktoberfest

#2661 feat(ui): bump web-console version to 0.0.8
  core/pom.xml
Labels: UI

#2631 feat(sql): add lpad and rpad string functions
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactoryTest.java
Labels: New feature, SQL, Hacktoberfest

#2666 chore(sql): add buffer size checks to lpad and rpad functions
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ReplaceStrFunctionFactory.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactoryTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Tidy up

#2657 fix(sql): avoid unexpected errors when over() clause for analytic function is missing
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlExecutionContext.java
  core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/analytic/AnalyticContext.java
  core/src/main/java/io/questdb/griffin/engine/analytic/AnalyticContextImpl.java
  core/src/main/java/io/questdb/griffin/engine/functions/analytic/RankFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java
  core/src/test/java/io/questdb/cairo/AllowAllSqlSecurityContext.java
  core/src/test/java/io/questdb/cutlass/text/SqlExecutionContextStub.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/griffin/WriteApplyLogTest.java
  core/src/test/java/io/questdb/griffin/engine/analytic/AnalyticFunctionTest.java
  core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
Labels: Bug, SQL, Tidy up

#2668 chore(core): fix fuzzy test in line protocol (#2340)
  core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpCommitTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/load/TableData.java
Labels: Schrödinger's bug

#2644 feat(sql): implement function split_part()
  core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/str/SplitPartFunctionFactoryTest.java
Labels: New feature, SQL, Hacktoberfest

#2674 chore(sql): remove rank() function temporarily, it is unstable
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/analytic/AnalyticFunctionTest.java
Labels: Bug, Tidy up

#2676 test(ilp): fix flaky test
  core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java
Labels: ILP, Flaky Test

#2683 fix(sql): fix copy from file with raw timestamp
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
  core/src/test/java/io/questdb/griffin/CopyTest.java
  core/src/test/resources/csv/test-quotes-rawts.csv
Labels: Bug, SQL, Tidy up

#2685 fix(sql): fix spurious ambiguous column name error with sample by and `joins`
  core/src/main/java/io/questdb/griffin/SqlException.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/griffin/SqlParserUpdateTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL
