Repository questdb/questdb, pull requests merged in 2022-09, with the labels that each got.

#2490 fix(core): fix missing native function on freebsd
  core/src/main/c/freebsd/files.c
Labels: Bug

#2488 fix(core): fix segfault crash on o3 sort of string null values
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/test/java/io/questdb/griffin/O3Test.java
Labels: Bug, Core

#2484 fix(sql): fix invalid column error in group by based on function key
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/griffin/KeyedAggregationTest.java
Labels: Bug, SQL

#2492 fix(sql): fix race condition in `where` execution logic
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameReducer.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilterAtom.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java
  core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java
Labels: Bug, SQL

#2493 chore(sql): improve alter table syntax error message
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/griffin/AlterTableDetachPartitionTest.java
Labels: SQL, Tidy up

#2496 chore(core): add missing Assert.fail() calls to failure scenario tests
  core/src/main/java/io/questdb/cairo/RebuildColumnBase.java
  core/src/test/java/io/questdb/cairo/FullFwdDataFrameCursorTest.java
  core/src/test/java/io/questdb/cairo/TableReaderMetadataCorruptionTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
  core/src/test/java/io/questdb/griffin/AlterTableAttachPartitionTest.java
  core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
Labels: Tidy up

#2508 chore(core): replace busy spinning with LockSupport#park() in count down latches
  benchmarks/src/main/java/org/questdb/SOCountDownLatchBenchmark.java
  benchmarks/src/main/java/org/questdb/TableWriteBenchmark.java
  core/src/main/java/io/questdb/mp/SOCountDownLatch.java
  core/src/main/java/io/questdb/mp/SOUnboundedCountDownLatch.java
Labels: Tidy up, Core

#2498 chore(sql): decrease memory footprint of idle HTTP and PG Wire connections
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/network/DefaultIODispatcherConfiguration.java
  core/src/main/java/io/questdb/std/Unsafe.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: Postgres Wire, REST API, ILP, Tidy up

#2526 chore(core): mark table busy exceptions as non-critical
  core/src/main/java/io/questdb/cairo/EntryUnavailableException.java
  core/src/main/java/io/questdb/cairo/pool/ex/EntryLockedException.java
  core/src/test/java/io/questdb/griffin/TruncateTest.java
Labels: Tidy up

#2524 feat(sql): add column pre-touch for parallel filter
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilterAtom.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/cairo/AbstractCairoTest.java
  core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java
  core/src/test/java/io/questdb/griffin/CompiledFilterTest.java
  core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Performance

#2530 chore(sql): add DEALLOCATE statement support
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/CompiledQuery.java
  core/src/main/java/io/questdb/griffin/CompiledQueryImpl.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
Labels: SQL, Compatibility

#2533 chore(http): change log level to critical for unexpected errors
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
Labels: REST API, Tidy up

#2535 fix(sql): fix UnsupportedOperationException on group by over empty table
  core/src/main/java/io/questdb/griffin/engine/EmptyTableRecordCursor.java
  core/src/test/java/io/questdb/griffin/NoopGroupByTest.java
  core/src/test/java/io/questdb/griffin/engine/table/EmptyTableRecordCursorTest.java
Labels: Bug, SQL

#2531 chore(sql): enable column pre-touch in parallel filter by default
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Tidy up

#2537 chore(pgwire): fix log level for SqlException
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
Labels: Tidy up

#2540 fix(sql): fix UnsupportedOperationException thrown on sample by with invalid values
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/WhereClauseParser.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByCursor.java
  core/src/test/java/io/questdb/griffin/SampleBySqlParserTest.java
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#2528 fix(sql): clear all fields of execution plan objects to avoid unexpected errors
  core/src/main/java/io/questdb/griffin/model/ExpressionNode.java
  core/src/main/java/io/questdb/griffin/model/QueryColumn.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/main/java/io/questdb/std/IntHashSet.java
  core/src/main/java/io/questdb/std/IntList.java
  core/src/main/java/io/questdb/std/LowerCaseCharSequenceHashSet.java
  core/src/main/java/io/questdb/std/LowerCaseCharSequenceIntHashMap.java
  core/src/main/java/io/questdb/std/LowerCaseCharSequenceObjHashMap.java
  core/src/test/java/io/questdb/griffin/model/QueryModelTest.java
  core/src/test/java/io/questdb/std/IntHashSetTest.java
  core/src/test/java/io/questdb/std/IntListTest.java
  core/src/test/java/io/questdb/std/LowerCaseCharSequenceHashSetTest.java
  core/src/test/java/io/questdb/std/LowerCaseCharSequenceIntHashMapTest.java
  core/src/test/java/io/questdb/std/LowerCaseCharSequenceObjHashMapTest.java
Labels: SQL, Tidy up

#2545 chore(core): bump web-console version to 0.0.5
  core/pom.xml
Labels: UI

#2546 fix(ilp): reduce ILP queue contention
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java
Labels: Performance

#2542 fix(core): fix O3 table write, which can produce 0 values on column files over 2Gb
  core/src/main/c/linux/files.c
  core/src/main/c/share/files.c
  core/src/main/c/share/files.h
  core/src/main/c/windows/files.c
  core/src/main/java/io/questdb/cairo/O3CopyJob.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/osx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/FilesTest.java
  core/src/test/java/io/questdb/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/griffin/O3Test.java
Labels: Bug, Core

#2544 chore(core): fix incorrect default values in built-in config files
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/cairo/vm/AbstractMemoryCR.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryPARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryW.java
  core/src/main/java/io/questdb/cairo/vm/api/NullMemory.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java
  core/src/main/java/io/questdb/cutlass/http/processors/QueryCache.java
  core/src/main/java/io/questdb/griffin/engine/AbstractRedBlackTree.java
  core/src/main/java/io/questdb/griffin/engine/LimitOverflowException.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java
  core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java
  core/src/main/java/io/questdb/jit/FiltersCompiler.java
  core/src/main/java/io/questdb/mp/AbstractSequence.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/FilesFacade.java
  core/src/main/java/io/questdb/std/FilesFacadeImpl.java
  core/src/main/java/io/questdb/std/IntLongAssociativeCache.java
  core/src/main/java/io/questdb/std/Unsafe.java
  core/src/main/java/io/questdb/std/datetime/millitime/DateFormatUtils.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/griffin/engine/AbstractFunctionFactoryTest.java
  core/src/test/java/io/questdb/std/IntLongAssociativeCacheTest.java
  core/src/test/java/io/questdb/std/fastdouble/AbstractDoubleHandPickedTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Tidy up

#2548 chore(ilp): reducing ILP writer idle timeout default settings
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: ILP, Tidy up

#2547 chore(core): add missing pause calls to busy spin loops
  core/src/main/java/io/questdb/cairo/ColumnPurgeJob.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/VacuumColumnVersions.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
  core/src/main/java/io/questdb/cutlass/http/WaitProcessor.java
  core/src/main/java/io/questdb/griffin/PurgingOperator.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/FlushQueryCacheFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/ops/OperationFutureImpl.java
  core/src/main/java/io/questdb/mp/MCSequence.java
  core/src/main/java/io/questdb/network/AbstractIODispatcher.java
  core/src/main/java/io/questdb/tasks/TelemetryTask.java
Labels: Tidy up
