Repository questdb/questdb, pull requests merged in 2022-07, with the labels that each got.

#2290 feat(core): use critical level to log all unhandled errors
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/pool/WriterPool.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java
  core/src/main/java/io/questdb/log/Log.java
  core/src/main/java/io/questdb/log/Logger.java
  core/src/main/java/io/questdb/log/SyncLogger.java
  core/src/main/java/io/questdb/mp/Worker.java
  core/src/test/java/io/questdb/log/LogAlertSocketTest.java
  core/src/test/java/io/questdb/network/NetTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Tidy up, Core

#2305 chore(test): fix flaky test DropIndexTest.testDropIndexSimultaneously
  core/src/test/java/io/questdb/griffin/DropIndexTest.java
Labels: Flaky Test

#2312 chore(core): improve io_uring prototype
  core/src/main/c/linux/io_uring.c
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/IOUring.java
  core/src/main/java/io/questdb/std/IOUringAccessor.java
  core/src/main/java/io/questdb/std/IOUringFacade.java
  core/src/main/java/io/questdb/std/IOUringFacadeImpl.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/std/IOUringTest.java
Labels: Tidy up

#2323 chore(ILP): move Sender to io.questdb.client
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
  core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
  core/src/main/java/io/questdb/cutlass/line/tcp/DelegatingTlsChannel.java
  core/src/main/java/module-info.java
  core/src/test/java/io/questdb/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/cutlass/line/interop/TestInterop.java
  core/src/test/java/io/questdb/cutlass/line/tcp/DelegatingTlsChannelTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpSenderTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTlsTcpSenderTest.java
Labels: Java, ILP

#2325 chore(ILP): sender API examples
  core/src/test/java/io/questdb/client/example/SenderExamples.java
Labels: ILP

#2324 fix(ILP): change default Sender port
  core/src/main/java/io/questdb/client/Sender.java
Labels: Bug, ILP

#2336 fix(sql): incorrect result for negative limit query with indexed symbol filter
  core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursor.java
  core/src/test/java/io/questdb/griffin/LimitTest.java
Labels: Bug, SQL

#2343 chore(sql): speed up sequential reads via io_uring in parallel import
  core/src/main/java/io/questdb/cutlass/text/TextImportTask.java
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
Labels: Bug, SQL, Performance

#2344 chore(core): optimize cqe polling in io_uring
  core/src/main/c/linux/io_uring.c
  core/src/main/java/io/questdb/std/IOURing.java
  core/src/main/java/io/questdb/std/IOURingImpl.java
  core/src/main/java/io/questdb/std/IOUringAccessor.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
  core/src/test/java/io/questdb/std/IOURingImplTest.java
Labels: Performance

#2251 feat(sql): implement function `substring`
  core/src/main/java/io/questdb/griffin/engine/functions/str/SubStringFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/functions/str/SubStringFunctionFactoryTest.java
Labels: New feature, SQL

#2365 chore(sql): test speedup
  core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
Labels: SQL
