Repository questdb/questdb, pull requests merged in 2022-06, with the labels that each got.

#2180 chore(benchmark): add j.u.HashMap for comparison in map benchmarks
  benchmarks/src/main/java/org/questdb/QMapReadRandomKeyBenchmark.java
  benchmarks/src/main/java/org/questdb/QMapReadSequentialKeyBenchmark.java
  benchmarks/src/main/java/org/questdb/QMapWriteBenchmark.java
Labels: Tidy up

#2198 fix(ilp): fix failed ILP auth key verification on certain keys
  core/src/main/java/io/questdb/cutlass/line/tcp/AuthDb.java
  core/src/test/java/io/questdb/cutlass/line/tcp/AuthDbTest.java
Labels: Bug, ILP, Security

#2093 fix(sql): Duplicate column names in create table, create from select, insert and update statements result in an error.
  benchmarks/src/main/java/org/questdb/ForLoopOverObjListVsLCCSHashSetBenchmark.java
  core/src/main/java/io/questdb/cairo/CairoException.java
  core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java
  core/src/main/java/io/questdb/cairo/RebuildColumnBase.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/SqlException.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/main/java/io/questdb/griffin/engine/join/JoinRecordMetadata.java
  core/src/main/java/io/questdb/griffin/model/CreateTableModel.java
  core/src/main/java/io/questdb/griffin/model/InsertModel.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/test/java/io/questdb/cairo/GenericRecordMetadataTest.java
  core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/griffin/AsOfJoinTest.java
  core/src/test/java/io/questdb/griffin/DBeaverTest.java
  core/src/test/java/io/questdb/griffin/FullFatJoinNoLeakTest.java
  core/src/test/java/io/questdb/griffin/JoinTest.java
  core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
  core/src/test/java/io/questdb/griffin/SqlExceptionTest.java
  core/src/test/java/io/questdb/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/griffin/SqlParserUpdateTest.java
  core/src/test/java/io/questdb/griffin/TableWriterAsyncCmdTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/conditional/CoalesceFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
  core/src/test/java/io/questdb/griffin/engine/join/JoinRecordMetadataTest.java
Labels: Bug

#2217 fix(ui): Fix `select build()` being called repeatedly
  ui/src/scenes/Footer/BuildVersion/index.tsx
  ui/src/scenes/Footer/BuildVersion/services.ts
Labels: Bug, UI

#2220 chore(ilp): make sure to reset symbol cache capacity when ILP connection is closed
  core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java
  core/src/main/java/io/questdb/cutlass/line/tcp/SymbolCache.java
  core/src/main/java/io/questdb/std/ObjIntHashMap.java
  core/src/test/java/io/questdb/cairo/SymbolMapTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/SymbolCacheTest.java
  core/src/test/java/io/questdb/std/ObjIntHashMapTest.java
Labels: ILP, Tidy up

#2258 chore: native binary build for armosx
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
Labels: Bug, Core

#2255 chore(test): improve stability of flush query cache tests
  core/src/test/java/io/questdb/cutlass/http/HttpFlushQueryCacheTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGFlushQueryCacheTest.java
Labels: Tidy up, Schrödinger's bug

#2263 fix(sql): fix potential resource leak on update statement release
  core/src/main/java/io/questdb/cairo/pool/WriterPool.java
  core/src/main/java/io/questdb/cairo/sql/ReaderOutOfDateException.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/engine/ops/OperationFutureImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/UpdateOperation.java
Labels: Bug, SQL, Schrödinger's bug

#2264 chore(test): fix flaky flush query cache tests for pg wire
  core/src/test/java/io/questdb/cutlass/pgwire/PGFlushQueryCacheTest.java
Labels: Schrödinger's bug

#2278 fix(sql): fix infinite loop in SAMPLE BY month over first or last values and indexed column filter
  core/src/main/java/io/questdb/griffin/engine/groupby/MonthTimestampSampler.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java
  core/src/test/java/io/questdb/griffin/engine/groupby/MonthTimestampSamplerTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#2273 fix(cairo): fixed SQL `update` index maintenance issues
  core/src/main/java/io/questdb/cairo/ColumnVersionReader.java
  core/src/main/java/io/questdb/cairo/IndexBuilder.java
  core/src/main/java/io/questdb/cairo/RebuildColumnBase.java
  core/src/main/java/io/questdb/cairo/RecoverVarIndex.java
  core/src/main/java/io/questdb/cairo/TableReader.java
  core/src/main/java/io/questdb/cairo/TableReaderMetadata.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/TxReader.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/UpdateOperator.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java
  core/src/test/java/io/questdb/cairo/ColumnVersionWriterTest.java
  core/src/test/java/io/questdb/cairo/IndexBuilderTest.java
  core/src/test/java/io/questdb/cairo/RecoverVarIndexTest.java
  core/src/test/java/io/questdb/griffin/SnapshotTest.java
  core/src/test/java/io/questdb/griffin/UpdateTest.java
  utils/src/main/java/io/questdb/cliutil/CmdUtils.java
Labels: Bug, SQL

#2276 fix(griffin): fix fd leak in tables() function
  core/src/main/java/io/questdb/cairo/TableReaderMetadata.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java
  core/src/test/java/io/questdb/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGFunctionsTest.java
  core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
Labels: Bug, SQL

#2284 fix(sql): fix crash for group by on cross join with aggregate sub-query
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java
  core/src/test/java/io/questdb/griffin/GroupByFunctionTest.java
Labels: Bug, SQL

#2282 fix(sql): fix table reader leak in over partition by symbol column queries
  core/src/main/java/io/questdb/cairo/RecordChain.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/griffin/SqlParserTest.java
Labels: Bug, SQL
