Repository questdb/questdb, pull requests merged in 2023-10, with the labels that each got.

#3797 fix(core): workaround for broken file locking on Docker Desktop on MacOS
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/std/Files.java
Labels: Bug, Java, Compatibility, Core

#3803 chore(core): add configurable per-class guaranteed logging
  ci/qlog.conf
  core/src/main/java/io/questdb/log/GuaranteedLogger.java
  core/src/main/java/io/questdb/log/LogFactory.java
Labels: tandem

#3817 fix(ilp): faster ILP authentication
  core/src/main/java/io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java
Labels: Performance, ILP, a hunch

#3818 feat(core): add `mkdir.mode` permission config for detached partitions
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/resources/server.conf
Labels: Enhancement, hacktoberfest

#3820 fix(sql): fix table name case sensitivity in SQL UPDATE
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/UpdateTest.java
Labels: Bug, SQL, hacktoberfest

#3819 fix(core): use the same GC algorithm in Docker image as with other QuestDB distros
  core/docker-entrypoint.sh
Labels: Bug, hacktoberfest, hacktoberfest-accepted

#3821 chore(core): fix benchmark compilation
  benchmarks/src/main/java/org/questdb/LineTCPSenderMain.java
Labels: Tidy up

#3830 fix(core): fix connection error to HTTP TCP port on MacOS
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/line/tcp/PlainTcpLineChannel.java
  core/src/main/java/io/questdb/log/LogAlertSocket.java
  core/src/main/java/io/questdb/network/AbstractIODispatcher.java
  core/src/main/java/io/questdb/network/Net.java
  core/src/main/java/io/questdb/network/NetworkFacade.java
  core/src/main/java/io/questdb/network/NetworkFacadeImpl.java
Labels: Core

#3831 docs(core): add section about the cloud to Spanish README
  i18n/README.es-es.md
Labels: Documentation

#3834 fix(sql): fix ArrayIndexOutOfBoundsException in select distinct with duplicate columns
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/test/java/io/questdb/test/griffin/DistinctTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/CountTest.java
Labels: Bug, SQL

#3873 feat(sql): add first and last boolean aggregation functions
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstBooleanGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstBooleanGroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastBooleanGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastBooleanGroupByFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/FirstBooleanGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/LastBooleanGroupByFunctionFactoryTest.java
Labels: Enhancement, SQL

#3844 fix(core): fix intermittent writing failures
  core/src/main/java/io/questdb/cairo/pool/WriterPool.java
  core/src/test/java/io/questdb/test/cairo/CairoEngineTest.java
Labels: Java, Core

#3879 feat(sql): add first and last string aggregation functions
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastStrGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastStrGroupByFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/FirstAndLastStrGroupByFunctionFactoryTest.java
Labels: Enhancement, SQL

#3866 chore(core): service account cookie
  core/src/main/java/io/questdb/DefaultFactoryProvider.java
  core/src/main/java/io/questdb/DefaultHttpClientConfiguration.java
  core/src/main/java/io/questdb/FactoryProvider.java
  core/src/main/java/io/questdb/FactoryProviderImpl.java
  core/src/main/java/io/questdb/HttpClientConfiguration.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cutlass/Services.java
  core/src/main/java/io/questdb/cutlass/http/DefaultHttpContextConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/DefaultHttpCookieHandler.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/HttpConstants.java
  core/src/main/java/io/questdb/cutlass/http/HttpContextConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/HttpCookieHandler.java
  core/src/main/java/io/questdb/cutlass/http/HttpHeaderParser.java
  core/src/main/java/io/questdb/cutlass/http/HttpResponseHeader.java
  core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java
  core/src/main/java/io/questdb/cutlass/http/HttpServer.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClientCookieHandler.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClientCookieHandlerFactory.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClientMain.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/test/java/io/questdb/test/griffin/AlterTableDropColumnTest.java
Labels: tandem

#3892 test(http): increase Socket timeout in MockAlertTarget
  core/src/test/java/io/questdb/test/log/MockAlertTarget.java
Labels: Java, Flaky Test

#3885 feat(sql): add vwap aggregation function
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/VwapDoubleGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/VwapDoubleGroupByFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/VwapDoubleGroupByFunctionFactoryTest.java
Labels: Enhancement, SQL

#3854 chore(sql): improve FastMap's memory layout
  benchmarks/src/main/java/org/questdb/FastMapReadBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapReadLongBenchmark.java
  core/src/main/java/io/questdb/cairo/map/CompactMapValue.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/cairo/map/FastMapCursor.java
  core/src/main/java/io/questdb/cairo/map/FastMapRecord.java
  core/src/main/java/io/questdb/cairo/map/FastMapValue.java
  core/src/main/java/io/questdb/cairo/map/MapValue.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SimpleMapValue.java
  core/src/main/java/io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java
  core/src/test/java/io/questdb/test/cairo/map/FastMapTest.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
Labels: SQL, Performance

#3896 chore(core): countDownLatch respects timeout in the presence of spurious wakeups
  core/src/main/java/io/questdb/mp/SOCountDownLatch.java
  core/src/test/java/io/questdb/test/mp/SOCountDownLatchTest.java
Labels: Bug, Java
