Repository questdb/questdb, pull requests merged in 2023-05, with the labels that each got.

#3237 fix(pgwire): fix Rust sqlx crate
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Labels: Bug, Postgres Wire

#3287 chore(core): add two tests to exmplify use of double quotes in references to columns in ORDER BY clauses
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
Labels: Enhancement, SQL, Core

#3302 fix(sql): unhandled ArrayIndexOutOfBoundsException in ASOF and LT JOIN on empty table
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/AsOfJoinTest.java
Labels: Bug, SQL

#3305 fix(sql): fix COPY performance for pre-created tables with non-default symbol capacity
  core/src/main/java/io/questdb/cairo/MapWriter.java
  core/src/main/java/io/questdb/cairo/SymbolMapWriter.java
  core/src/main/java/io/questdb/cairo/vm/NullMapWriter.java
  core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java
  core/src/main/java/io/questdb/cutlass/text/types/TypeAdapter.java
Labels: Bug, Performance

#3292 feat(http): introduce configuration for health check pessimism
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cutlass/Services.java
  core/src/main/java/io/questdb/cutlass/http/DefaultHttpContextConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/HttpContextConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/HttpMinServerConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/processors/HealthCheckProcessor.java
  core/src/main/java/io/questdb/griffin/engine/functions/StrArrayFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/CurrentSchemasFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/StringToStringArrayFunction.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/cutlass/http/HealthCheckTest.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpHealthCheckTestBuilder.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpServerConfigurationBuilder.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/StrArrayFunctionTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/CurrentSchemasFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/StringToStringArrayFunctionTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Bug, Enhancement, SQL, REST API

#3325 fix(http): format query parameter ignored by /imp endpoint
  core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessorState.java
  core/src/test/java/io/questdb/test/cutlass/http/ImportIODispatcherTest.java
Labels: Bug, REST API

#3183 fix(core): copy metadata associated with wal tables on backup
  core/src/main/java/io/questdb/cairo/TableNameRegistryFileStore.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/wal/WalWriterMetadata.java
  core/src/main/java/io/questdb/griffin/ExpressionParser.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java
  core/src/test/java/io/questdb/test/griffin/TableBackupTest.java
Labels: Bug

#3333 fix(sql): NullPointerException on join with function filter
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/test/java/io/questdb/test/griffin/JoinTest.java
Labels: Bug, SQL

#3334 fix(sql): UnsupportedOperationException on join with constant non-boolean filter expression
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/test/java/io/questdb/test/griffin/JoinTest.java
Labels: Bug, SQL

#3338 fix(sql): timeout of CREATE TABLE AS SELECT leaves leaked entry in table registry
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/test/cairo/CreateTableTest.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpQueryTestBuilder.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Labels: Bug, SQL

#2929 feat(sql): enable rank() analytical SQL function
  core/Dockerfile
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/engine/analytic/AnalyticFunctionTest.java
Labels: SQL, Tidy up

#3239 feat(sql): add QuestDB to string returned by version() function
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/Constants.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Labels: Enhancement, Compatibility

#3364 fix(ilp): remove wrong db/ segment from ILP auth config path
  core/src/main/java/io/questdb/ServerMain.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/ServerMainIlpAuthTest.java
Labels: Bug, ILP

#3410 chore(core): avoid type pollution in WalWriter
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
Labels: Tidy up

#3406 chore(core): replace table name reserved error with table does not exist in some cases
  core/src/main/java/io/questdb/cairo/CairoEngine.java
Labels: Bug, Core
