Repository questdb/questdb, pull requests merged in 2023-01, with the labels that each got.

#2890 feat(sql): add trigonometric functions sin, cos, tan, cot, asin, acos, atan, atan2, toRadians, fromRadians, pi
  core/src/main/java/io/questdb/griffin/engine/functions/math/AcosDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/AsinDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/Atan2DoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/AtanDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/CosDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/CotDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/DegreesDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/PIDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/RadiansDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SinDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/TanDoubleFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/griffin/engine/AbstractFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/AcosDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/AsinDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/Atan2DoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/AtanDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CosDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/CotDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/DegreesDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/RadiansDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/SinDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/TanDoubleFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/math/TrigonometryTest.java
Labels: New feature, Core

#2889 perf(sql): unrolled group by functions in GroupByFunctionsUpdater
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractGroupByFunctionsUpdater.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByFunctionsUpdater.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByFunctionsUpdaterFactory.java
Labels: SQL, Performance

#2839 fix(sql): fix internal error when using empty quoted strings in queries
  core/src/main/java/io/questdb/griffin/ExpressionParser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/main/java/io/questdb/griffin/model/ExpressionNode.java
  core/src/main/java/io/questdb/std/GenericLexer.java
  core/src/main/java/io/questdb/std/str/AbstractCharSequence.java
  core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/griffin/model/ExpressionNodeTest.java
  core/src/test/java/io/questdb/std/GenericLexerTest.java
Labels: Bug, Core

#2871 feat(core): improve instance start-up speed
  core/src/main/java/io/questdb/std/datetime/DateLocale.java
  core/src/main/java/io/questdb/std/datetime/DateLocaleFactory.java
Labels: Performance

#2779 feat(core): support partition by ISO week and ISO week format
  core/src/main/java/io/questdb/cairo/PartitionBy.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampCeilFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java
  core/src/main/java/io/questdb/std/datetime/microtime/GenericTimestampFormat.java
  core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatCompiler.java
  core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatUtils.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/cairo/FullFwdDataFrameCursorTest.java
  core/src/test/java/io/questdb/cairo/PartitionByTest.java
  core/src/test/java/io/questdb/cairo/TableReaderReloadTest.java
  core/src/test/java/io/questdb/cairo/TableReaderTailRecordCursorTest.java
  core/src/test/java/io/questdb/cairo/TableReaderTest.java
  core/src/test/java/io/questdb/cairo/TableWriterTest.java
  core/src/test/java/io/questdb/griffin/AlterTableDropPartitionTest.java
  core/src/test/java/io/questdb/griffin/CopyTest.java
  core/src/test/java/io/questdb/griffin/InsertTest.java
  core/src/test/java/io/questdb/griffin/TimestampQueryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/date/TimestampCeilFloorFunctionFactoryTest.java
  core/src/test/java/io/questdb/std/datetime/microtime/TimestampFormatCompilerTest.java
  core/src/test/java/io/questdb/std/datetime/microtime/TimestampsTest.java
Labels: Enhancement, SQL

#2903 feat(sql): optimize hash map used in joins, group by, sample by and other queries
  benchmarks/src/main/java/org/questdb/FastMapReadRandomKeyBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapReadSequentialKeyBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapWriteBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapWriteLongBenchmark.java
  benchmarks/src/main/java/org/questdb/MemEqBenchmark.java
  core/src/main/c/share/asmlib/CMakeLists.txt
  core/src/main/c/share/dispatcher.h
  core/src/main/c/share/ooo.cpp
  core/src/main/c/share/ooo_dispatch.cpp
  core/src/main/c/share/ooo_dispatch.h
  core/src/main/c/share/ooo_dispatch_vanilla.cpp
  core/src/main/c/share/simd.h
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/map/CompactMapValue.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/cairo/map/FastMapCursor.java
  core/src/main/java/io/questdb/cairo/map/FastMapRecord.java
  core/src/main/java/io/questdb/cairo/map/FastMapValue.java
  core/src/main/java/io/questdb/cairo/map/MapFactory.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/LimitOverflowException.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/JoinRecordMetadata.java
  core/src/main/java/io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/union/SetRecordCursorFactoryConstructor.java
  core/src/main/java/io/questdb/griffin/engine/union/UnionRecordCursorFactory.java
  core/src/main/java/io/questdb/std/Hash.java
  core/src/main/java/io/questdb/std/Long256HashSet.java
  core/src/main/java/io/questdb/std/Long256Impl.java
  core/src/main/java/io/questdb/std/MemoryTag.java
  core/src/main/java/io/questdb/std/Vect.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/osx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/HashTest.java
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/cairo/map/FastMapTest.java
  core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java
  core/src/test/java/io/questdb/griffin/SecurityTest.java
  core/src/test/java/io/questdb/std/DirectLongListTest.java
  core/src/test/java/io/questdb/std/Long256HashSetTest.java
  core/src/test/java/io/questdb/std/VectTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Performance

#2918 chore(core): fix missing defaults for O3 min/max commit lag
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/PropServerConfigurationTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Tidy up

#2740 feat(core): support auto log file delete in rolling log writer
  core/src/main/java/io/questdb/log/LogRollingFileWriter.java
  core/src/main/java/io/questdb/std/Numbers.java
  core/src/main/resources/io/questdb/site/conf/log.conf
  core/src/test/java/io/questdb/log/LogFactoryTest.java
  core/src/test/java/io/questdb/std/NumbersTest.java
Labels: Enhancement

#2868 feat(core): use faster hash function in hash tables on ILP hot path
  benchmarks/src/main/java/org/questdb/ByteCharSequenceIntHashMapBenchmark.java
  benchmarks/src/main/java/org/questdb/CharSequenceHashFunctionBenchmark.java
  core/src/main/java/io/questdb/cairo/map/CompactMap.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cutlass/line/tcp/DirectByteSymbolLookup.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpUtils.java
  core/src/main/java/io/questdb/cutlass/line/tcp/NetworkIOJob.java
  core/src/main/java/io/questdb/cutlass/line/tcp/SymbolCache.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/std/ByteCharSequenceIntHashMap.java
  core/src/main/java/io/questdb/std/ByteCharSequenceObjHashMap.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/main/java/io/questdb/std/Hash.java
  core/src/main/java/io/questdb/std/ObjIntHashMap.java
  core/src/main/java/io/questdb/std/Unsafe.java
  core/src/main/java/io/questdb/std/fastdouble/FastDoubleSwar.java
  core/src/main/java/io/questdb/std/str/ByteCharSequence.java
  core/src/main/java/io/questdb/std/str/DirectByteCharSequence.java
  core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/BaseLineTcpContextTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpCommitFuzzTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/SymbolCacheTest.java
  core/src/test/java/io/questdb/std/ByteCharSequenceIntHashMapTest.java
  core/src/test/java/io/questdb/std/ByteCharSequenceObjHashMapTest.java
  core/src/test/java/io/questdb/std/HashTest.java
  core/src/test/java/io/questdb/std/ObjIntHashMapTest.java
  core/src/test/java/io/questdb/std/fastdouble/FastDoubleMathTest.java
  core/src/test/resources/date_test.formats
  core/src/test/resources/hash/words.zip
Labels: Performance, ILP

#2924 fix(sql): fix long256 comparisons on different columns of the same table
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactory.java
  core/src/test/java/io/questdb/griffin/engine/AbstractFunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactoryTest.java
  core/src/test/java/io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactoryTest.java
Labels: Bug, SQL

#2928 fix(core): fix symbol reader lookups at minimal capacity
  core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java
  core/src/test/java/io/questdb/griffin/SymbolTest.java
Labels: Bug, SQL

#2933 chore(sql): fix broken test in line tcp/udp
  core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpPartitionReadOnlyTest.java
  core/src/test/java/io/questdb/cutlass/line/udp/LineUdpPartitionReadOnlyTest.java
Labels: Bug

#2938 chore(core): fix more flapping tests
  core/src/main/java/io/questdb/cairo/ColumnPurgeOperator.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/IDGenerator.java
  core/src/main/java/io/questdb/cairo/TxnScoreboard.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java
  core/src/main/java/io/questdb/cairo/vm/Vm.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java
  core/src/main/java/io/questdb/cutlass/text/CsvFileIndexer.java
  core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java
  core/src/main/java/io/questdb/cutlass/text/SerialCsvFileImporter.java
  core/src/main/java/io/questdb/cutlass/text/TextImportTask.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java
  core/src/main/java/io/questdb/log/LogAlertSocketWriter.java
  core/src/main/java/io/questdb/log/LogRollingFileWriter.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/FilesFacade.java
  core/src/main/java/io/questdb/std/FilesFacadeImpl.java
  core/src/main/java/io/questdb/std/fastdouble/FastDouble.java
  core/src/main/java/io/questdb/std/fastdouble/FastDoubleByteArray.java
  core/src/main/java/io/questdb/std/fastdouble/FastDoubleCharArray.java
  core/src/main/java/io/questdb/std/fastdouble/FastDoubleMem.java
  core/src/main/java/io/questdb/std/fastdouble/FastFloat.java
  core/src/main/java/io/questdb/std/fastdouble/FastFloatByteArray.java
  core/src/main/java/io/questdb/std/fastdouble/FastFloatCharArray.java
  core/src/test/java/io/questdb/FilesTest.java
  core/src/test/java/io/questdb/cairo/TableReaderTest.java
  core/src/test/java/io/questdb/cairo/TableWriterTest.java
  core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverTest.java
  core/src/test/java/io/questdb/griffin/AddIndexTest.java
  core/src/test/java/io/questdb/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
  core/src/test/java/io/questdb/log/LogAlertSocketWriterTest.java
  core/src/test/java/io/questdb/std/TestFilesFacadeImpl.java
  core/src/test/java/io/questdb/std/fastdouble/AbstractDoubleHandPickedTest.java
  core/src/test/java/io/questdb/std/fastdouble/AbstractFloatHandPickedTest.java
Labels: Schrödinger's bug

#2923 fix(sql): fix timestamp column required error in sample by with sub-queries
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/griffin/FunctionParser.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/test/java/io/questdb/cairo/FullFwdDataFrameCursorTest.java
  core/src/test/java/io/questdb/cairo/TableWriterTest.java
  core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#2935 chore(core): avoid GC in rolling log writer
  core/src/main/java/io/questdb/log/LogRollingFileWriter.java
  core/src/main/java/io/questdb/std/Files.java
  core/src/main/java/io/questdb/std/FilesFacadeImpl.java
  core/src/main/java/io/questdb/std/MemoryTag.java
  core/src/main/java/io/questdb/std/Numbers.java
  core/src/main/java/io/questdb/std/datetime/DateFormat.java
  core/src/main/java/io/questdb/std/str/DirectCharSink.java
  core/src/main/resources/io/questdb/site/conf/log.conf
  core/src/test/java/io/questdb/log/LogFactoryTest.java
  core/src/test/java/io/questdb/log/TemplateParserTest.java
  core/src/test/java/io/questdb/std/NumbersTest.java
Labels: Tidy up, Core

#2944 chore(core): add WAL writer metrics
  core/src/main/java/io/questdb/cairo/pool/WalWriterPool.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
  core/src/main/java/io/questdb/cairo/wal/WalMetrics.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/resources/io/questdb/site/conf/log.conf
Labels: New feature

#2945 fix(sql): fix incorrect results caused by SQL optimiser pushing down some filters to nested SAMPLE BY aggregation
  core/src/main/java/io/questdb/griffin/SqlKeywords.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/log/LogAlertSocket.java
  core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
  core/src/test/java/io/questdb/log/LogAlertSocketTest.java
  core/src/test/java/io/questdb/log/MockAlertTarget.java
Labels: Bug, SQL
