Repository questdb/questdb, pull requests merged in 2023-08, with the labels that each got.

#3566 feat(core): data deduplication on multiple columns
  core/CMakeLists.txt
  core/src/main/c/share/bit_vector.h
  core/src/main/c/share/dedup.cpp
  core/src/main/c/share/ooo.cpp
  core/src/main/c/share/ooo_dispatch.h
  core/src/main/c/share/util.h
  core/src/main/java/io/questdb/cairo/DedupColumnCommitAddresses.java
  core/src/main/java/io/questdb/cairo/O3PartitionJob.java
  core/src/main/java/io/questdb/cairo/TableColumnMetadata.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/vm/AbstractMemoryCR.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryCARW.java
  core/src/main/java/io/questdb/cairo/vm/api/NullMemory.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/WalWriterMetadata.java
  core/src/main/java/io/questdb/cairo/wal/seq/SequencerMetadata.java
  core/src/main/java/io/questdb/cairo/wal/seq/SequencerMetadataService.java
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java
  core/src/main/java/io/questdb/griffin/engine/table/ShowColumnsRecordCursorFactory.java
  core/src/main/java/io/questdb/std/ObjList.java
  core/src/main/java/io/questdb/std/Vect.java
  core/src/main/resources/io/questdb/bin/armlinux/libquestdb.so
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/osx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/test/ServerMainForeignTableTest.java
  core/src/test/java/io/questdb/test/TelemetryTest.java
  core/src/test/java/io/questdb/test/cairo/TableUtilsTest.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java
  core/src/test/java/io/questdb/test/fuzz/FuzzStableInsertOperation.java
  core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java
  core/src/test/java/io/questdb/test/griffin/ShowTablesTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/geohash/GeoHashQueryTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
  core/src/test/java/io/questdb/test/std/VectTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Enhancement

#3613 chore(core): fix work dir sensivity in questdb.sh
  core/src/main/bin/env.sh
  core/src/main/bin/questdb.sh
Labels: Tidy up

#3620 fix(core): avoid unbounded growth of transactions in O3 lag of WAL tables
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/AbstractCairoTest.java
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/cairo/CairoTestConfiguration.java
  core/src/test/java/io/questdb/test/cairo/ConfigurationOverrides.java
  core/src/test/java/io/questdb/test/cairo/Overrides.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
  core/src/test/java/io/questdb/test/cutlass/text/CairoConfigurationWrapper.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/WalTableListFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Enhancement, Core

#3626 fix(sql): truncate nanos in textual timestamps
  core/src/main/java/io/questdb/griffin/model/IntervalUtils.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
  core/src/test/java/io/questdb/test/griffin/model/IntervalUtilsTest.java
Labels: Bug, SQL, Java, Grafana, Compatibility, Friction

#3629 chore(core): remove circular dependency between CairoEngine and FactoryProvider
  core/src/main/java/io/questdb/DefaultFactoryProvider.java
  core/src/main/java/io/questdb/FactoryProvider.java
  core/src/main/java/io/questdb/FactoryProviderImpl.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/DdlListenerFactory.java
  core/src/main/java/io/questdb/cairo/DdlListenerFactoryImpl.java
  core/src/main/java/io/questdb/cairo/DefaultDdlListener.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/pool/WalWriterPool.java
  core/src/main/java/io/questdb/cairo/pool/WriterPool.java
  core/src/main/java/io/questdb/cairo/wal/DefaultWalInitializer.java
  core/src/main/java/io/questdb/cairo/wal/DefaultWalListener.java
  core/src/main/java/io/questdb/cairo/wal/WalInitializerFactory.java
  core/src/main/java/io/questdb/cairo/wal/WalListener.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cutlass/text/CopyTask.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/test/java/io/questdb/test/cairo/pool/WriterPoolTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalListenerTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
Labels: Tidy up, Core, tandem

#3568 chore(core): refactor code to support acl update on table or column rename
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/DdlListener.java
  core/src/main/java/io/questdb/cairo/DefaultDdlListener.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/wal/MetadataService.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/seq/SequencerMetadataService.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java
  core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java
  core/src/main/java/io/questdb/cutlass/text/CopyRequestJob.java
  core/src/main/java/io/questdb/cutlass/text/CopyTask.java
  core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java
Labels: tandem

#3630 chore(core): SimpleWaitingLock liveness improvements and simplification
  core/src/main/java/io/questdb/mp/SimpleWaitingLock.java
Labels: Bug, Java, Core

#3585 chore(core): authorize table reindex
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/std/Misc.java
  core/src/test/java/io/questdb/test/cairo/CairoEngineTest.java
Labels: tandem

#3628 fix(sql): fix UUID binding variables in WAL tables
  core/src/main/java/io/questdb/cairo/wal/WalEventCursor.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/UuidTest.java
Labels: Bug, SQL, Java

#3638 fix(http): avoid running out of memory when importing partitioned table over REST API
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/wal/MetadataService.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/seq/MetadataServiceStub.java
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java
  core/src/main/java/io/questdb/cutlass/text/TextLoader.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java
  core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
Labels: Bug, REST API

#3633 feat(sql): add column type validation for ALTER COLUMN statements
  core/src/main/java/io/questdb/cairo/ColumnPurgeJob.java
  core/src/main/java/io/questdb/cairo/GenericTableRecordMetadata.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
  core/src/main/java/io/questdb/cairo/wal/OperationExecutor.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/griffin/CompiledQuery.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/std/Transient.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
  core/src/test/java/io/questdb/test/griffin/AddIndexTest.java
  core/src/test/java/io/questdb/test/griffin/AlterTableAlterSymbolColumnCacheFlagTest.java
  core/src/test/java/io/questdb/test/griffin/DropIndexTest.java
  core/src/test/java/io/questdb/test/griffin/InsertTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalAlterTableSqlTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
Labels: Bug, SQL

#3652 chore(sql): add simple tool to produce content for repo sql-grammar ts files
  utils/src/main/java/io/questdb/misc/SqlGrammarUtil.java
Labels: Enhancement

#3625 chore(core): support pending table renames, sequencer drop delay
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/TableNameRegistry.java
  core/src/main/java/io/questdb/cairo/TableNameRegistryFileStore.java
  core/src/main/java/io/questdb/cairo/TableNameRegistryRO.java
  core/src/main/java/io/questdb/cairo/TableNameRegistryRW.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
  core/src/main/java/io/questdb/cairo/wal/CheckWalTransactionsJob.java
  core/src/main/java/io/questdb/cairo/wal/DefaultWalInitializer.java
  core/src/main/java/io/questdb/cairo/wal/WalInitializer.java
  core/src/main/java/io/questdb/cairo/wal/WalPurgeJob.java
  core/src/main/java/io/questdb/cairo/wal/WalUtils.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/seq/EmptyOperationCursor.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableMetadataChangeLog.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalListenerTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalPurgeJobTest.java
Labels: tandem

#3637 chore(wal): unify WalListener API
  core/src/main/java/io/questdb/cairo/wal/DefaultWalListener.java
  core/src/main/java/io/questdb/cairo/wal/WalListener.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java
  core/src/test/java/io/questdb/test/cairo/wal/WalListenerTest.java
Labels: tandem

#3662 fix(sql): fix SAMPLE BY queries with ORDER BY timestamp DESC
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL, Java

#3660 fix(sql): fix SAMPLE BY fill(null) and fill(value) to support timestamps
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNullRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL, Java

#3631 feat(sql): add SHOW commands for ACL
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/test/griffin/SqlKeywordsTest.java
Labels: SQL

#3691 fix(sql): allow quotes around dedup keys
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java
Labels: Bug

#3696 docs(core): create doc template
  .github/ISSUE_TEMPLATE/doc_request.yaml
Labels: Documentation

#3697 chore(core): add authorizeSelectOnAnyColumn method
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java
Labels: tandem
