Repository questdb/questdb, pull requests merged in 2023-07, with the labels that each got.

#3525 chore(ilp): add insert permission checks for ILP/TCP
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/cairo/TableWriterTest.java
  core/src/test/java/io/questdb/test/cutlass/line/AbstractLinePartitionReadOnlyTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpPartitionReadOnlyTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/udp/LineUdpPartitionReadOnlyTest.java
  core/src/test/java/io/questdb/test/cutlass/line/udp/UdpLineChannelTest.java
Labels: ILP

#3542 fix(sql): fix like/ilike filter on bind variable expression
  core/src/main/java/io/questdb/griffin/engine/functions/bind/NamedParameterLinkFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/bind/UuidBindVariable.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/AbstractO3Test.java
  core/src/test/java/io/questdb/test/griffin/O3FailureFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
Labels: Bug, SQL

#3546 chore(core): make DROP statement compatible with ENT
  core/src/main/java/io/questdb/griffin/SqlCompiler.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/DropStatementTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: Bug

#3540 chore(core): introduce separate set of permissions for ILP
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java
  core/src/test/java/io/questdb/test/griffin/AsyncOffloadTest.java
Labels: Bug, Security

#3552 chore(core): remove redundant security context call
  core/src/main/java/io/questdb/cairo/CairoEngine.java
Labels: Tidy up

#3565 fix(sql): unexpected NullPointerException on COUNT(SELECT ...) query
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/CountTest.java
Labels: Bug, SQL

#3559 feat(sql): implement function to convert two longs to UUID
  core/src/main/java/io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/UuidTest.java
Labels: SQL

#3567 feat(core): enable prepending jvm flags from docker run
  core/docker-entrypoint.sh
Labels: Enhancement, integration

#3599 fix(ilp): fix race condition in ILP authentication
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/ConcurrentTcpSenderBootstrapTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpContextTest.java
Labels: Bug, ILP
