Repository questdb/questdb, pull requests merged in 2023-12, with the labels that each got.

#4020 test(core): improve FuzzRunner
  core/src/main/java/io/questdb/cairo/sql/TableMetadata.java
  core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java
  core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
Labels: Tidy up

#4024 perf(sql): execute complex sum aggregates on short column in parallel
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractCovarGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractStdDevGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CorrGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/GroupByRewriteTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/SumIntVecGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/SumShortVecGroupByFunctionFactoryTest.java
Labels: SQL, Performance

#4025 perf(sql): optimize order by designated timestamp and other columns with limit
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizePartiallySortedLightRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/OrderByWithFilterTest.java
Labels: SQL, Performance

#4033 fix(sql): fix edge case internal error in case-switch expression
  core/src/main/java/io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java
Labels: Bug, SQL

#4008 feat(core): add support for configurable JVM flags using environment variables
  core/src/main/bin/questdb.sh
Labels: New feature

#4038 perf(sql): get rid of offset packing in FastMap
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/std/MemoryTag.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Performance

#4000 fix(sql): occasionally failing queries when under rapid structural changes
  core/src/main/java/io/questdb/cairo/sql/TableReferenceOutOfDateException.java
  core/src/main/java/io/questdb/cairo/sql/WriterOutOfDateException.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/InsertOperationImpl.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGMultiStatementMessageTest.java
  core/src/test/java/io/questdb/test/griffin/InsertTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Labels: Bug, SQL

#4050 feat(sql): add sign() functions
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignByteFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignDoubleFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignFloatFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignIntFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignLongFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/SignShortFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/math/SignFunctionFactoryTest.java
Labels: New feature, SQL

#4059 chore(core): user enabled and endpoint permission checks on every query
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContextFactory.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContextFactory.java
  core/src/main/java/io/questdb/cairo/security/SecurityContextFactory.java
  core/src/main/java/io/questdb/cutlass/auth/Authenticator.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/cutlass/pgwire/ReadOnlyUsersAwareSecurityContextFactory.java
Labels: tandem

#4063 feat(sql): add `nullif(double, double)` SQL function
  core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfDoubleFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/NullIfFunctionFactoryTest.java
Labels: Enhancement, SQL

#4023 chore(core): set guaranteed loggers from test
  ci/qlog.conf
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/log/GuaranteedLogger.java
  core/src/main/java/io/questdb/log/LogFactory.java
  core/src/main/java/io/questdb/log/SyncLogger.java
  core/src/test/java/io/questdb/test/AbstractBootstrapTest.java
  core/src/test/java/io/questdb/test/log/LogFactoryTest.java
  utils/src/main/java/io/questdb/cliutil/RebuildIndex.java
  utils/src/main/java/io/questdb/cliutil/RecoverVarIndex.java
  utils/src/main/java/io/questdb/cliutil/Table2Ilp.java
  utils/src/main/java/io/questdb/cliutil/TxSerializer.java
Labels: tandem

#4044 chore(core): refactor metadata infrastructure
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/TableWriterMetadata.java
  core/src/main/java/io/questdb/cairo/pool/PoolListener.java
  core/src/main/java/io/questdb/cairo/pool/SequencerMetadataPool.java
  core/src/main/java/io/questdb/cairo/pool/TableMetadataPool.java
  core/src/main/java/io/questdb/cairo/pool/TableReaderMetadataPool.java
  core/src/main/java/io/questdb/cairo/wal/WalApplySqlExecutionContext.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlExecutionContext.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/ShowTablesFunctionFactory.java
  core/src/test/java/io/questdb/test/cairo/TableMetadataTest.java
  core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java
  core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/O3MaxLagTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
  core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
Labels: tandem

#4077 fix(ilp): ilp@http small fixes
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessorState.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/http/TestHttpClient.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpFailureTests.java
Labels: tandem
