Repository questdb/questdb, pull requests merged in 2024-04, with the labels that each got.

#4367 fix(sql): fix error in some CASE statements when ELSE branch is missing
  core/src/main/java/io/questdb/griffin/ExpressionParser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: Bug, SQL

#4364 chore(sql): fix nulls interpreted as empty varchars in update statements
  core/src/main/java/io/questdb/griffin/engine/functions/CharFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/IPv4Function.java
  core/src/main/java/io/questdb/griffin/engine/functions/Long128Function.java
  core/src/main/java/io/questdb/griffin/engine/functions/Long256Function.java
  core/src/main/java/io/questdb/griffin/engine/functions/StrFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/SymbolFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastCharToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastDateToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastDoubleToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastFloatToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIPv4ToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIntToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastLongToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastStrToVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/cast/CastTimestampToVarcharFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/UpdateTest.java
Labels: Bug, SQL

#4370 chore(core): fix deadlock on shutdown
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java
  core/src/main/java/io/questdb/std/str/Path.java
  core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java
  core/src/test/java/io/questdb/test/ServerMainForeignTableTest.java
  core/src/test/java/io/questdb/test/cairo/CairoEngineTest.java
  core/src/test/java/io/questdb/test/cairo/CreateTableTest.java
  core/src/test/java/io/questdb/test/cairo/TableNameRegistryTest.java
  core/src/test/java/io/questdb/test/cairo/pool/WriterPoolTest.java
  core/src/test/java/io/questdb/test/cairo/vm/ContiguousMemoryMTest.java
  core/src/test/java/io/questdb/test/cairo/wal/TableSequencerImplTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderFailureTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/AlterWalTableLineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverDropTableFuzzTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverUpdateFuzzTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGMultiStatementMessageTest.java
  core/src/test/java/io/questdb/test/griffin/AlterTableDetachPartitionTest.java
  core/src/test/java/io/questdb/test/griffin/CopyTest.java
  core/src/test/java/io/questdb/test/griffin/DropIndexTest.java
  core/src/test/java/io/questdb/test/griffin/O3PartitionPurgeTest.java
  core/src/test/java/io/questdb/test/griffin/O3Test.java
  core/src/test/java/io/questdb/test/griffin/SnapshotTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
  core/src/test/java/io/questdb/test/griffin/UpdateConcurrentTest.java
  core/src/test/java/io/questdb/test/griffin/wal/ConcurrentWalTableRenameTest.java
  core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
  core/src/test/java/io/questdb/test/std/str/PathTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Bug, tandem

#4371 perf(ilp): optimize ingestion for tables with large number of columns
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/std/AbstractLowerCaseCharSequenceHashSet.java
  core/src/main/java/io/questdb/std/BitSet.java
  core/src/main/java/io/questdb/std/str/Utf8Sequence.java
  core/src/main/java/io/questdb/std/str/Utf8StringSink.java
  core/src/test/java/io/questdb/test/std/BitSetTest.java
Labels: Performance, ILP

#4372 fix(ilp): fix 'maximum buffer size exceeded' in ILP client
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
Labels: Bug, Java, ILP

#4387 chore(ilp): log buffer size changes as debug
  core/src/main/java/io/questdb/cutlass/line/tcp/PlainTcpLineChannel.java
Labels: Java

#4388 chore(sql): simpify offset calculation in varchar null check JIT code
  core/src/main/c/share/jit/avx2.h
  core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
  core/src/main/resources/io/questdb/bin/linux/libquestdb.so
  core/src/main/resources/io/questdb/bin/osx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
Labels: SQL

#4385 feat(ilp): Sender config string can disable individual flush types separately
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
Labels: Java, ILP

#4391 feat(ilp): client configuration string supports auto_flush_bytes
  core/src/main/java/io/questdb/client/Sender.java
  core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpSenderTest.java
Labels: Java, ILP

#4384 fix(sql): constant in explicit group by should not remove parallel optimisation
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Labels: Bug, SQL, Performance

#4349 chore(core): improve startup text
  .gitignore
  core/src/main/bin/env.sh
  core/src/main/bin/print-hello.sh
  core/src/main/bin/questdb.exe
  core/src/main/bin/questdb.sh
  core/src/main/java/io/questdb/Bootstrap.java
  core/src/main/java/io/questdb/DefaultBootstrapConfiguration.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/log/LogFactory.java
  win64svc/CMakeLists.txt
  win64svc/src/CMakeLists.txt
  win64svc/src/common.h
  win64svc/src/questdb.c
  win64svc/src/service.c
Labels: Enhancement, Core

#4394 chore(ilp): add ilp-from-conf sample
  examples.manifest.yaml
Labels: Documentation, Java

#4398 feat(sql): add milliseconds and microseconds support to datediff
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampDiffFunctionFactory.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampDiffFunctionFactoryTest.java
Labels: Enhancement, SQL

#4396 feat(sql): add milliseconds and microseconds support to dateadd
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampAddFunctionFactoryTest.java
Labels: Enhancement, SQL

#4359 chore(sql): optimize varchar like operator for short contains patterns
  core/src/main/java/io/questdb/cutlass/text/AbstractTextLexer.java
  core/src/main/java/io/questdb/cutlass/text/CsvFileIndexer.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/std/SwarUtils.java
  core/src/main/java/io/questdb/std/str/Utf8Sequence.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/std/SwarUtilsTest.java
Labels: SQL, Performance

#4397 fix(http): client to process data received before TLS close_notification
  core/src/main/java/io/questdb/network/JavaTlsClientSocket.java
Labels: Bug, Java, ILP

#4400 chore(core): fix queue reuse code
  core/src/main/java/io/questdb/MessageBusImpl.java
  core/src/main/java/io/questdb/cutlass/text/AbstractTextLexer.java
  core/src/main/java/io/questdb/mp/AbstractMSequence.java
  core/src/main/java/io/questdb/mp/AbstractSSequence.java
  core/src/main/java/io/questdb/mp/Barrier.java
  core/src/main/java/io/questdb/mp/FanOut.java
  core/src/main/java/io/questdb/mp/MCSequence.java
  core/src/main/java/io/questdb/mp/OpenBarrier.java
  core/src/main/java/io/questdb/mp/SCSequence.java
Labels: Bug, Bug 0

#4410 chore(build): upgrade nodejs version used by Danger
  .github/workflows/danger.yml
Labels: Compatibility

#4405 chore(core): add support for varchar-typed arguments to functions
  core/src/main/java/io/questdb/cairo/ColumnType.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/griffin/RecordToRowCopierUtils.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/test/java/io/questdb/test/griffin/VarcharConversionTest.java
Labels: Bug, SQL

#4411 fix(sql): fix incorrect results for parallel group by with symbol like filter
  core/src/main/java/io/questdb/griffin/engine/functions/BinaryFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/UnaryFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/AllNotEqStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/AllNotEqVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolCursorFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/columns/Long256Column.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/SizePrettyFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
Labels: Bug, SQL

#4408 fix(sql): internal error when inserting null string as a designated timestamp
  core/src/main/java/io/questdb/griffin/InsertRowImpl.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/DateConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/DoubleConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/FloatConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/GeoByteConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/GeoIntConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/GeoLongConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/GeoShortConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/IPv4Constant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/IntConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/Long128Constant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/Long256Constant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/LongConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/NullBinConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/StrConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/SymbolConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/TimestampConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/UuidConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/constants/VarcharConstant.java
  core/src/test/java/io/questdb/test/griffin/InsertCastTest.java
  core/src/test/java/io/questdb/test/griffin/InsertNullTest.java
  core/src/test/java/io/questdb/test/griffin/InsertTest.java
  core/src/test/java/io/questdb/test/griffin/O3Test.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/constants/ConstantsTest.java
Labels: Bug

#4420 fix(sql): fix stuck parallel group by query due to incorrect query timeout handling
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByMergeShardJob.java
  core/src/main/java/io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java
Labels: Bug, SQL

#4425 chore(core): zero out unused inlined varchar bytes
  core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
Labels: Core

#4404 fix(sql): fix SAMPLE BY queries with functions in SELECT clause
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/ServerMainShowPartitionsTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#4415 chore(sql): InTimestampTimestampFunctionFactory Varchar support
  core/src/main/java/io/questdb/griffin/FunctionParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampVarcharFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/TimestampQueryTest.java
  core/src/test/java/io/questdb/test/griffin/WhereClauseParserTest.java
Labels: SQL, Java

#4392 fix(sql): FILL(LINEAR) now supports ALIGN TO CALENDAR
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/HaversineDistDegreeGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MaxDoubleGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MaxFloatGroupByFunctionTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#4414 chore(sql): avoid indirect conversion UTF-8 -> UTF-16 -> (Long256 and GeoHash)
  core/src/main/java/io/questdb/cairo/GeoHashes.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
  core/src/main/java/io/questdb/cairo/vm/AbstractMemoryCR.java
  core/src/main/java/io/questdb/cairo/vm/MemoryPARWImpl.java
  core/src/main/java/io/questdb/cairo/vm/NullMemoryMR.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryA.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryCARW.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryR.java
  core/src/main/java/io/questdb/cairo/vm/api/NullMemory.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/cairo/wal/WriterRowUtils.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineWalAppender.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableStructureAdapter.java
  core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
  core/src/main/java/io/questdb/cutlass/text/types/GeoHashAdapter.java
  core/src/main/java/io/questdb/griffin/RecordToRowCopierUtils.java
  core/src/main/java/io/questdb/griffin/SqlUtil.java
  core/src/main/java/io/questdb/griffin/engine/functions/bind/BindVariableServiceImpl.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
  core/src/test/java/io/questdb/test/cairo/GeoHashesTest.java
  core/src/test/java/io/questdb/test/cairo/TableWriterTest.java
  core/src/test/java/io/questdb/test/cairo/vm/MemoryCARWImplTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
  core/src/test/java/io/questdb/test/std/str/Utf8sTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: SQL, Performance

#4433 fix(sql): FILL(LINEAR) regression in 7.4.1
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
Labels: Bug, SQL

#4389 chore(core): new properties on settings endpoint
  core/src/main/java/io/questdb/BuildInformation.java
  core/src/main/java/io/questdb/BuildInformationHolder.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/ServerConfiguration.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/TelemetryTest.java
  core/src/test/java/io/questdb/test/cutlass/http/SettingsEndpointTest.java
Labels: tandem

#4442 perf(sql): improve performance of length(VARCHAR)
  core/src/main/java/io/questdb/griffin/engine/functions/str/LengthVarcharFunctionFactory.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
Labels: Enhancement, SQL, Performance

#4459 chore(core): sync OSS and Ent
  core/src/main/java/io/questdb/std/Chars.java
  core/src/test/java/io/questdb/test/std/str/CharsTest.java
  core/src/test/java/io/questdb/test/std/str/PathTest.java
Labels: tandem

#4463 chore(core): zero extra null varchar bytes
  core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
Labels: Core
