Repository questdb/questdb, pull requests merged in 2024-01, with the labels that each got.

#4073 fix(sql): fix NullPointerException in replace() function with symbol arguments
  core/src/main/java/io/questdb/cutlass/pgwire/PGOids.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeCatalogueCursor.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ReplaceStrFunctionFactory.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/DBeaverTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/PgTypeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/str/ReplaceStrFunctionFactoryTest.java
Labels: Bug, SQL

#4096 chore(pgwire): reset recv buffer offsets when clearing context
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
Labels: Postgres Wire, tandem

#4094 chore(sql): remove CompactMap and fine-tune FastMap props
  benchmarks/src/main/java/org/questdb/FastMapMergeBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapReadBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapReadLongBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapWriteBenchmark.java
  benchmarks/src/main/java/org/questdb/FastMapWriteLongBenchmark.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/map/CompactMap.java
  core/src/main/java/io/questdb/cairo/map/CompactMapCursor.java
  core/src/main/java/io/questdb/cairo/map/CompactMapRecord.java
  core/src/main/java/io/questdb/cairo/map/CompactMapValue.java
  core/src/main/java/io/questdb/cairo/map/Map.java
  core/src/main/java/io/questdb/cairo/map/MapFactory.java
  core/src/main/java/io/questdb/cairo/map/MapKey.java
  core/src/main/java/io/questdb/cairo/map/MapRecord.java
  core/src/main/java/io/questdb/cairo/map/MapValue.java
  core/src/main/java/io/questdb/cairo/map/ShardedMapCursor.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByAtom.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByRecordCursorFactory.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/cairo/map/CompactMapTest.java
  core/src/test/java/io/questdb/test/cairo/map/FastMapTest.java
  core/src/test/java/io/questdb/test/griffin/JoinTest.java
  core/src/test/java/io/questdb/test/griffin/Long128Tests.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: SQL, Tidy up

#4101 chore(sql): fix query registry with acl issues
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/engine/RegisteredRecordCursorFactory.java
Labels: tandem

#4102 fix(sql): fix potential races when regexp_replace function is used in where or group by clause
  core/src/main/java/io/questdb/cairo/map/FastMap.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByTest.java
Labels: Bug, SQL

#4103 fix(core): fix edge case error when importing a large CSV file
  core/src/main/java/io/questdb/cutlass/text/CopyTask.java
Labels: Bug

#4116 chore(core): improve table name logging in WAL Apply Job
  core/src/main/java/io/questdb/cairo/vm/MemoryCMORImpl.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
Labels: tandem

#4113 fix(sql): unregister query on cursor initialization failure
  core/src/main/java/io/questdb/griffin/engine/RegisteredRecordCursorFactory.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Labels: Bug, SQL

#4132 fix(http): fix CSV import for files larger than 2GB
  benchmarks/pom.xml
  core/pom.xml
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/HttpHeaderParser.java
  core/src/main/java/io/questdb/cutlass/http/HttpRequestHeader.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpHeaderParserTest.java
  examples/pom.xml
  pom.xml
  utils/pom.xml
Labels: Bug, REST API

#4148 perf(sql): avoid redundant disk reads in ORDER BY + LIMIT queries with parallel filter
  core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/SortAndLimitTest.java
Labels: SQL, Performance

#4157 fix(sql): fix exception when running insert as select
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
  utils/src/main/java/io/questdb/cliutil/Table2IlpCopier.java
Labels: Bug, SQL

#4175 feat(conf): add new configuration settings to server.conf (including Enterprise settings)
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: tandem

#4153 fix(core): fix invalid table writer state after ALTER TABLE SQUASH PARTITIONS
  core/src/main/java/io/questdb/cairo/AbstractIndexReader.java
  core/src/main/java/io/questdb/cairo/BitmapIndexBwdReader.java
  core/src/main/java/io/questdb/cairo/BitmapIndexFwdReader.java
  core/src/main/java/io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
  core/src/test/java/io/questdb/test/griffin/O3SquashPartitionTest.java
Labels: Bug, Core
