Repository questdb/questdb, pull requests merged in 2024-03, with the labels that each got.

#4257 chore(core): create _txn file as last step
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
Labels: tandem

#4269 fix(core): TLS handshake might occasionally get stuck on MacOS
  core/src/main/java/io/questdb/network/IODispatcherOsx.java
Labels: Bug, Java, Core

#4255 fix(sql): fix incorrect unordered map creation check
  core/src/main/java/io/questdb/cairo/map/Map.java
  core/src/main/java/io/questdb/cairo/map/MapFactory.java
  core/src/main/java/io/questdb/cairo/map/OrderedMap.java
  core/src/main/java/io/questdb/cairo/map/Unordered16Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered2Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered4Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered8Map.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/std/Hash.java
  core/src/main/java/io/questdb/std/Vect.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: Bug, Performance

#4270 fix(sql): fix altering table to add index can remove dedup key
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java
Labels: Bug, Core

#4272 fix(core): fix wal table is suspended after invalid drop partition SQL
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
  core/src/test/java/io/questdb/test/std/str/DirectUtf8SinkTest.java
Labels: Bug, Core

#4248 chore(ilp): implement min request throughput in Java ILP Sender
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/MockHttpProcessor.java
Labels: Java, ILP

#4277 feat(sql): change default behaviour of SAMPLE BY to ALIGN TO CALENDAR instead of ALIGN TO FIRST OBSERVATION
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/cairo/BitmapIndexFwdNullReader.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainQuerySmokeTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/cairo/Overrides.java
  core/src/test/java/io/questdb/test/griffin/AggregateTest.java
  core/src/test/java/io/questdb/test/griffin/AlterTableAttachPartitionFromSoftLinkTest.java
  core/src/test/java/io/questdb/test/griffin/AlterTableDetachPartitionTest.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/IPv4Test.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/RecordCursorMemoryUsageTest.java
  core/src/test/java/io/questdb/test/griffin/SecurityTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserUpdateTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctIPv4GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctIntGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctLongGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CharGroupByFunctionTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountStringGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/FirstSymbolGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/FloatGroupByFunctionsTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/LastSymbolGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MaxStrGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MinStrGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByFunctionCaseTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByConfigTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
  core/src/test/java/io/questdb/test/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
  core/src/test/resources/server.conf
Labels: Enhancement, SQL

#4246 chore(http): bypass authentication for static content delivery
  core/src/main/java/io/questdb/FactoryProvider.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cutlass/http/DefaultRejectProcessorFactory.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/RejectProcessorFactory.java
  core/src/main/java/io/questdb/cutlass/http/processors/RejectProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/RejectProcessorImpl.java
  core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/resources/server.conf
Labels: tandem

#4289 chore(ilp): fix auto_flush_interval default
  core/src/main/java/io/questdb/client/Sender.java
Labels: Bug, ILP, Compatibility

#4295 chore(http): increase HTTP max connections limit to 256
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: REST API, ILP

#4292 chore(core): json types in web console settings
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java
  core/src/test/java/io/questdb/test/cutlass/http/SettingsEndpointTest.java
Labels: tandem

#4274 fix(sql): qualified names in ORDER BY join queries no longer cause AssertionError
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinNoKeyFastRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/LtJoinNoKeyFastRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: Bug, SQL

#4304 chore(build): test compilation issues
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpSenderTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByUtf8SinkTest.java
Labels: Bug, CI

#4287 feat(sql): breaking change💥 - change default behaviour of CREATE TABLE AS/INSERT INTO SELECT statements to be non-atomic and batched
  benchmarks/src/main/java/org/questdb/CreateTableAsSelectBenchmark.java
  benchmarks/src/main/java/org/questdb/InsertIntoSelectBenchmark.java
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlKeywords.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/model/CreateTableModel.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/cairo/Overrides.java
  core/src/test/java/io/questdb/test/griffin/CreateTableAsSelectTest.java
  core/src/test/java/io/questdb/test/griffin/InsertTest.java
  core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/TableRepairTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
  core/src/test/resources/server.conf
  pkg/ami/marketplace/assets/server.conf
Labels: Enhancement, SQL

#4319 chore(core): tidy up
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/main/java/io/questdb/griffin/engine/functions/StrFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/VarcharFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/InformationSchemaTablesFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/KeywordsFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PgAttributeFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PgExtensionFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PgGetKeywordsFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PgNamespaceRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeCatalogueCursor.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java
  core/src/main/java/io/questdb/std/Chars.java
Labels: tandem

#4325 chore(ilp): configuration string schema is case sensitive
  core/src/main/java/io/questdb/client/impl/ConfStringParser.java
  core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/test/client/impl/ConfStringParserTest.java
Labels: Bug, ILP, Compatibility

#4321 fix(sql): fix ILIKE for upper case non-ASCII patterns
  core/src/main/java/io/questdb/cairo/RecordSinkFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/LikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/cairo/RecordSinkFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/std/str/CharsTest.java
  core/src/test/java/io/questdb/test/std/str/Utf8sTest.java
Labels: Bug, SQL

#4345 chore(core): add -n switch to the usage string in shell script
  core/src/main/bin/questdb.sh
Labels: Documentation, Core

#4346 chore(core): use the managed temp file in LogFactoryTest
  core/src/test/java/io/questdb/test/log/LogFactoryTest.java
Labels: Enhancement, Core

#4309 chore(core): optimized VARCHAR equality function
  core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
  core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java
  core/src/main/java/io/questdb/griffin/FunctionParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqVarcharStrFunctionFactory.java
  core/src/main/java/io/questdb/std/str/DirectUtf8Sequence.java
  core/src/main/java/io/questdb/std/str/InlinedVarchar.java
  core/src/main/java/io/questdb/std/str/Utf8Sequence.java
  core/src/main/java/io/questdb/std/str/Utf8SplitString.java
  core/src/main/java/io/questdb/std/str/Utf8String.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
  core/src/test/java/io/questdb/test/cairo/VarcharEqualsTest.java
  core/src/test/java/io/questdb/test/cairo/VarcharTypeDriverTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/PageFrameCursorTest.java
Labels: Enhancement, SQL, Performance, Core

#4348 perf(core): improve hash table lookup performance for small string keys such as column names and symbols
  benchmarks/src/main/java/org/questdb/GroupByLong128HashSetBenchmark.java
  benchmarks/src/main/java/org/questdb/GroupByLong256HashSetBenchmark.java
  benchmarks/src/main/java/org/questdb/GroupByLongHashSetBenchmark.java
  benchmarks/src/main/java/org/questdb/HyperLogLogBenchmark.java
  benchmarks/src/main/java/org/questdb/StringHashFunctionBenchmark.java
  benchmarks/src/main/java/org/questdb/Utf8StringIntHashMapBenchmark.java
  core/src/main/java/io/questdb/cairo/map/MapKey.java
  core/src/main/java/io/questdb/cairo/map/MapRecord.java
  core/src/main/java/io/questdb/cairo/map/OrderedMap.java
  core/src/main/java/io/questdb/cairo/map/OrderedMapFixedSizeRecord.java
  core/src/main/java/io/questdb/cairo/map/OrderedMapVarSizeRecord.java
  core/src/main/java/io/questdb/cairo/map/ShardedMapCursor.java
  core/src/main/java/io/questdb/cairo/map/Unordered16Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered16MapRecord.java
  core/src/main/java/io/questdb/cairo/map/Unordered2Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered2MapRecord.java
  core/src/main/java/io/questdb/cairo/map/Unordered4Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered4MapRecord.java
  core/src/main/java/io/questdb/cairo/map/Unordered8Map.java
  core/src/main/java/io/questdb/cairo/map/Unordered8MapRecord.java
  core/src/main/java/io/questdb/cutlass/line/tcp/SymbolCache.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByIntHashSet.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLong128HashSet.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLong256HashSet.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLongHashSet.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByAtom.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByRecordCursorFactory.java
  core/src/main/java/io/questdb/std/AbstractLongHashSet.java
  core/src/main/java/io/questdb/std/CharSequenceIntHashMap.java
  core/src/main/java/io/questdb/std/ConcurrentLongHashMap.java
  core/src/main/java/io/questdb/std/Hash.java
  core/src/main/java/io/questdb/std/LongLongHashSet.java
  core/src/main/java/io/questdb/std/Utf8StringIntHashMap.java
  core/src/main/java/io/questdb/std/Utf8StringObjHashMap.java
  core/src/main/java/io/questdb/std/Uuid.java
  core/src/main/java/io/questdb/std/str/DirectUtf8Sink.java
  core/src/test/java/io/questdb/test/cairo/map/MapTest.java
  core/src/test/java/io/questdb/test/cairo/map/OrderedMapTest.java
  core/src/test/java/io/questdb/test/cairo/map/Unordered2MapTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalTableWriterFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/test/griffin/UuidTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByIntHashSetTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByLong128HashSetTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByLong256HashSetTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByLongHashSetTest.java
  core/src/test/java/io/questdb/test/std/HashTest.java
  core/src/test/java/io/questdb/test/std/LongLongHashSetTest.java
Labels: Performance, ILP
