Repository questdb/questdb, pull requests merged in 2024-11, with the labels that each got.

#5119 fix(core): fix http client handling of cookies
  core/src/main/java/io/questdb/cutlass/http/HttpCookie.java
  core/src/main/java/io/questdb/cutlass/http/HttpHeaderParser.java
  core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatUtils.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpHeaderParserTest.java
Labels: tandem

#5092 chore(sql): more precise version of regr_slope
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/CovarSampleGroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/RegressionSlopeFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/VarPopGroupByFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/groupby/VarSampleGroupByFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/RegressionSlopeFunctionFactoryTest.java
Labels: SQL

#5134 fix(ilp): Java ILP client supports timestamps up to 9999-12-31 23:59:59.999999
  core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
  core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
  core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineProtocolException.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineWalAppender.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
  core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampsTest.java
Labels: Bug, ILP

#5078 fix(http): send error to http client instead of closing connection
  core/src/main/java/io/questdb/cairo/CairoException.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/griffin/FunctionParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/http/TestHttpClient.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/SimulateCrashFunctionTest.java
Labels: Bug, tandem

#5135 perf(sql): use faster hash table in window functions
  core/src/main/java/io/questdb/griffin/engine/functions/window/AvgDoubleWindowFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/window/FirstValueDoubleWindowFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/window/RankFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/window/RowNumberFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionUnitTest.java
Labels: SQL, Performance

#5082 fix(sql): fix non-reporting of error for SQLs with multiple `where` clauses
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
  core/src/test/java/io/questdb/test/griffin/AlterTableDetachPartitionTest.java
  core/src/test/java/io/questdb/test/griffin/AsOfJoinTest.java
  core/src/test/java/io/questdb/test/griffin/CopyTest.java
  core/src/test/java/io/questdb/test/griffin/InsertTest.java
  core/src/test/java/io/questdb/test/griffin/WithClauseTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
  core/src/test/resources/sqllogictest/test/sql/functions.test
Labels: Bug, SQL

#5139 perf(sql): speed up negative limit queries with a wildcard
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Labels: SQL, Performance

#5132 fix(core): fix drop partition SQL not removing the expected partition data and in some rare circumstances leading to a data loss
  core/src/main/java/io/questdb/cairo/ColumnVersionReader.java
  core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/TxReader.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/test/java/io/questdb/test/cairo/ColumnVersionWriterTest.java
  core/src/test/java/io/questdb/test/cairo/TxnTest.java
  core/src/test/java/io/questdb/test/fuzz/FuzzCairoMetadata.java
  core/src/test/java/io/questdb/test/fuzz/FuzzChangeColumnTypeOperation.java
  core/src/test/java/io/questdb/test/fuzz/FuzzDropPartitionOperation.java
  core/src/test/java/io/questdb/test/fuzz/FuzzTransaction.java
  core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java
  core/src/test/java/io/questdb/test/griffin/AlterTableConvertPartitionTest.java
  core/src/test/java/io/questdb/test/griffin/FrameAppendFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/O3ParquetPartitionFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/ReaderReloadFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/CheckpointFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
  core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Enhancement, Core

#5175 chore(core): replace admin-only checks with permissions
  core/src/main/java/io/questdb/cairo/SecurityContext.java
  core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java
  core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
  core/src/main/java/io/questdb/griffin/QueryRegistry.java
  core/src/main/java/io/questdb/griffin/engine/functions/activity/QueryActivityFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpMemoryUsageFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpThreadStacksFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/FlushQueryCacheFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateWarningsFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndLogFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/table/HydrateTableMetadataFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/test/TestNPEFactory.java
  core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/activity/CancelQueryFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/activity/QueryActivityFunctionFactoryTest.java
Labels: Security, tandem

#5178 fix(sql): correctly escape double quotes when exporting CSVs
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessorState.java
  core/src/main/java/io/questdb/std/str/Utf8Sink.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpUtils.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/http/SendAndReceiveRequestBuilder.java
  core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java
Labels: Bug, REST API, Compatibility

#5181 chore(pgwire): better handling of statements executed at parse time
  core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java
  core/src/main/java/io/questdb/griffin/CompiledQuery.java
  core/src/main/java/io/questdb/griffin/CompiledQueryImpl.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Labels: Postgres Wire

#5182 chore(core): create/drop/truncate table query registry fix
  core/src/main/java/io/questdb/cairo/DdlListener.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/griffin/QueryBuilder.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/SqlParserCallback.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperation.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationBuilder.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationBuilderImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationFuture.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationImpl.java
  core/src/test/java/io/questdb/test/cairo/CreateTableTest.java
  core/src/test/java/io/questdb/test/cutlass/http/QueryRegistryTest.java
  core/src/test/java/io/questdb/test/griffin/CreateTableAsSelectTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Labels: tandem

#5166 fix(sql): breaking change 💥 - `dateadd(AIN)` will now error if provided invalid constant period or stride
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampAddFunctionFactoryTest.java
Labels: SQL

#5189 fix(pgwire): fix incorrect error reporting to PostgresSQL drivers
  ci/templates/start-self-hosted-job.yml
  core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java
  core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PreparedStatementInvalidationTest.java
Labels: Bug, Postgres Wire

#5193 chore(pgwire): send error message to client before closing connection during startup
  core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGTlsCompatTest.java
Labels: Postgres Wire, tandem
