Repository questdb/questdb, pull requests merged in 2024-07, with the labels that each got.

#4735 fix(http): missing varchar escaping quotes in CSV export
  core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Labels: Bug, REST API

#4728 perf(sql): optimize l2price with up to 5 argument pairs
  core/src/main/java/io/questdb/griffin/engine/functions/finance/LevelTwoPriceFunctionFactory.java
Labels: SQL, Performance

#4684 test(pgwire): stabilize E2E tests
  core/src/test/java/io/questdb/test/ServerMainFlushQueryCacheTest.java
  core/src/test/java/io/questdb/test/ServerMainQuerySmokeTest.java
Labels: Schrödinger's bug

#4742 fix(core): 💥 breaking change - enforce fail-fast on NFS
  core/src/main/java/io/questdb/Bootstrap.java
  core/src/main/java/io/questdb/std/Files.java
Labels: Java, Core

#4720 perf(sql): speed up self-join queries on symbol columns
  core/src/main/java/io/questdb/cairo/RecordSinkFactory.java
  core/src/main/java/io/questdb/cairo/sql/RecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByAtom.java
  core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java
  core/src/main/java/io/questdb/std/BitSet.java
  core/src/test/java/io/questdb/test/cairo/RecordChainTest.java
  core/src/test/java/io/questdb/test/cairo/RecordSinkFactoryTest.java
  core/src/test/java/io/questdb/test/cairo/map/OrderedMapTest.java
  core/src/test/java/io/questdb/test/griffin/AsOfJoinTest.java
  core/src/test/java/io/questdb/test/griffin/JoinTest.java
Labels: SQL, Performance

#4734 feat(sql): add mid price SQL function
  core/src/main/java/io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/finance/MidPriceFunctionFactoryTest.java
Labels: SQL

#4692 feat(sql): add variant of timestamp_floor supporting an offset origin
  core/src/main/java/io/questdb/cairo/PartitionBy.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorOffsetFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorOffsetFunctions.java
  core/src/main/java/io/questdb/griffin/model/IntervalUtils.java
  core/src/main/java/io/questdb/log/LogRollingFileWriter.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/cairo/IntervalBwdDataFrameCursorTest.java
  core/src/test/java/io/questdb/test/cairo/IntervalFwdDataFrameCursorTest.java
  core/src/test/java/io/questdb/test/cairo/TableReaderTest.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampFloorOffsetFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampsTest.java
Labels: Enhancement, SQL

#4755 test(sql): fuzz tests use strLen as maximum varchar length
  core/src/test/java/io/questdb/test/fuzz/FuzzInsertOperation.java
Labels: Bug, Flaky Test

#4706 perf(sql): more efficient pattern lookup for short ASCII patterns
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/std/SwarUtils.java
  core/src/test/java/io/questdb/test/std/SwarUtilsTest.java
Labels: SQL, Performance

#4690 feat(sql): increase coverage of SQL queries that use vectorized execution plan
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: SQL, Performance

#4762 fix(ilp): client - avoid spuriously sending duplicate data
  core/src/main/c/osx/kqueue.c
  core/src/main/resources/io/questdb/bin/darwin-aarch64/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/darwin-amd64/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/windows-amd64/libquestdb.dll
  core/src/main/resources/io/questdb/bin/windows-amd64/questdbr.dll
Labels: Bug, Core

#4710 chore(sql): clean up group by rewrite methods
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Labels: SQL

#4764 docs(ilp): changed examples to use trades table
  examples/src/main/java/com/example/sender/AuthExample.java
  examples/src/main/java/com/example/sender/AuthTlsExample.java
  examples/src/main/java/com/example/sender/BasicExample.java
  examples/src/main/java/com/example/sender/HttpAdvancedExample.java
  examples/src/main/java/com/example/sender/HttpExample.java
  examples/src/main/java/com/example/sender/HttpsAuthExample.java
Labels: Documentation, ILP

#4793 perf(core): speedup small transaction writing 50-100%
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfiguration.java
  core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java
  core/src/main/java/io/questdb/cairo/O3PartitionPurgeJob.java
  core/src/main/java/io/questdb/cairo/TableReader.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/vm/MemoryCMORImpl.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java
  core/src/main/java/io/questdb/cairo/wal/CheckWalTransactionsJob.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/main/java/io/questdb/log/AbstractLogRecord.java
  core/src/main/java/io/questdb/log/LogFactory.java
  core/src/main/java/io/questdb/log/LogRecord.java
  core/src/main/java/io/questdb/log/NullLogRecord.java
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/cairo/vm/ContiguousOffsetMappedMemoryTest.java
  core/src/test/java/io/questdb/test/cairo/wal/WalTableWriterFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/TimestampQueryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/bind/RegexpReplaceStrBindVariableTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
  core/src/test/java/io/questdb/test/log/LogAlertSocketTest.java
Labels: Performance

#4796 fix(sql): fix wrong results returned from parallel WHERE and GROUP BY for some function keys
  core/src/main/java/io/questdb/griffin/engine/functions/constants/StrTypeConstant.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/ToStrDateFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/ToStrTimestampFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LPadVarcharVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LTrimStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LeftStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/LeftVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RPadVarcharVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RTrimStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ReplaceStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ReplaceVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RightStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/RightVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/ToCharBinFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/TrimStrConstFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/TrimStrFunction.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/TrimStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/str/TrimVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/table/TouchTableFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/TimestampQueryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/bind/RegexpReplaceStrBindVariableTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/str/LTrimStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/str/RTrimStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/str/TrimStrFunctionFactoryTest.java
Labels: Bug, SQL

#4798 fix(sql): incorrect results returned from parallel GROUP BY with single varchar function key
  core/src/main/java/io/questdb/cairo/map/UnorderedVarcharMap.java
  core/src/main/java/io/questdb/std/str/DirectUtf8Sink.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Bug, SQL

#4745 fix(core): avoid table suspension when under memory pressure
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/CairoException.java
  core/src/main/java/io/questdb/cairo/O3CopyJob.java
  core/src/main/java/io/questdb/cairo/O3OpenColumnJob.java
  core/src/main/java/io/questdb/cairo/O3PartitionJob.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
  core/src/main/java/io/questdb/cairo/wal/O3JobParallelismRegulator.java
  core/src/main/java/io/questdb/cairo/wal/seq/SeqTxnTracker.java
  core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java
  core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java
  core/src/main/java/io/questdb/log/LogFactory.java
  core/src/test/java/io/questdb/test/AbstractCairoTest.java
  core/src/test/java/io/questdb/test/ServerMainCleanStartupTest.java
  core/src/test/java/io/questdb/test/cairo/RssMemoryLimitTest.java
  core/src/test/java/io/questdb/test/cairo/wal/seq/SeqTxnTrackerTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/AbstractLineHttpFuzzTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/HttpSenderMemoryPressureFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/WalTableListFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
Labels: Enhancement, Java, WAL

#4794 perf(sql): speed up like/ilike operator on symbol column
  core/src/main/java/io/questdb/griffin/ExpressionParser.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/engine/functions/eq/EqVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeSymbolFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeSymbolFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/LikeSymbolFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java
  core/src/main/java/module-info.java
  core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeSymbolFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeVarcharFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeStrFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeSymbolFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeVarcharFunctionFactoryTest.java
Labels: SQL, Performance

#4668 perf(sql): speed up regexp_replace(varchar) for simple patterns
  core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java
  core/src/main/java/io/questdb/std/str/Utf8s.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/std/str/Utf8sTest.java
Labels: SQL, Performance

#4804 fix(sql): some window functions might double count rows
  core/src/main/java/io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
Labels: Bug, SQL

#4733 feat(sql): introduce SAMPLE BY FROM-TO syntax for specifying result ranges
  core/src/main/java/io/questdb/cairo/sql/Function.java
  core/src/main/java/io/questdb/griffin/BasePlanSink.java
  core/src/main/java/io/questdb/griffin/PlanSink.java
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSplitVirtualRecordSampleByCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/AbstractVirtualRecordSampleByCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/MicroTimestampSampler.java
  core/src/main/java/io/questdb/griffin/engine/groupby/MonthTimestampSampler.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNoneNotKeyedRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNoneNotKeyedRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNullNotKeyedRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNullRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillPrevNotKeyedRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillPrevNotKeyedRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueNotKeyedRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueNotKeyedRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
  core/src/main/java/io/questdb/griffin/engine/groupby/TimestampSampler.java
  core/src/main/java/io/questdb/griffin/engine/groupby/YearTimestampSampler.java
  core/src/main/java/io/questdb/griffin/model/QueryModel.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/test/java/io/questdb/test/cutlass/suspend/TestCases.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/SampleBySqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserUpdateTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctIPv4GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctIntGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctLongGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountStringGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/MonthTimestampSamplerTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/TimestampSamplerFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/YearTimestampSamplerTest.java
  core/src/test/java/io/questdb/test/griffin/model/QueryModelTest.java
Labels: Enhancement, SQL

#4807 feat(core): trigger file to initiate snapshot recovery
  core/src/main/java/io/questdb/ServerMain.java
  core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java
  core/src/main/java/io/questdb/cairo/TableUtils.java
  core/src/test/java/io/questdb/test/griffin/SnapshotTest.java
  core/src/test/java/io/questdb/test/griffin/wal/SnapshotFuzzTest.java
  core/src/test/java/io/questdb/test/tools/TestUtils.java
Labels: Core, Friction

#4812 fix(sql): add support for filling weeks ('w') in SAMPLE BY queries
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueNotKeyedRecordCursor.java
  core/src/main/java/io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL
