Repository questdb/questdb, pull requests merged in 2024-02, with the labels that each got.

#4166 feat(ilp): Influx Line Protocol client configuration via strings
  core/pom.xml
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/client/impl/ConfStringParser.java
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/main/java/io/questdb/std/Chars.java
  core/src/main/java/io/questdb/std/str/Utf16Sink.java
  core/src/main/java/module-info.java
  core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java
  core/src/test/java/io/questdb/test/client/impl/ConfStringParserTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/AbstractLineHttpFuzzTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderFailureTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpsSenderTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpSenderTest.java
Labels: Enhancement, Java, ILP

#4192 fix(sql): fix NullPointerException in LATEST ON with nested query
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByIntHashSet.java
  core/src/main/java/io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java
  core/src/main/java/io/questdb/std/Hash.java
  core/src/test/java/io/questdb/test/griffin/LatestByTest.java
Labels: Bug, SQL

#4207 chore(build): use a free runner to build MacOS ARM binaries
  .github/workflows/rebuild_native_libs.yml
Labels: CI

#4205 fix(core): fix errors / data inconsistencies after restoring from a snapshot
  core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java
  core/src/main/java/io/questdb/cairo/MapWriter.java
  core/src/main/java/io/questdb/cairo/SymbolMapUtil.java
  core/src/main/java/io/questdb/cairo/SymbolMapWriter.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/TxWriter.java
  core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java
  core/src/main/java/io/questdb/cairo/wal/WalWriter.java
  core/src/test/java/io/questdb/test/cairo/SymbolMapTest.java
  core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
  core/src/test/java/io/questdb/test/griffin/wal/SnapshotFuzzTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
  core/src/test/java/io/questdb/test/griffin/wal/WalTelemetryTest.java
Labels: Bug, Core

#4190 perf(sql): improve parallel group by detection when aliasing columns
  core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
  core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: SQL, Performance

#4218 chore(core): bootstrap refactoring for extension
  core/src/main/java/io/questdb/Bootstrap.java
  core/src/test/java/io/questdb/test/BootstrapTest.java
Labels: tandem

#4220 chore(core): remove buffering for non-chunked responses in HttpClient
  compat/src/test/java/io/questdb/compat/HttpClientCompatTest.java
  core/src/main/java/io/questdb/cutlass/http/client/AbstractChunkedResponse.java
  core/src/main/java/io/questdb/cutlass/http/client/AbstractResponse.java
  core/src/main/java/io/questdb/cutlass/http/client/ChunkedResponse.java
  core/src/main/java/io/questdb/cutlass/http/client/Fragment.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClientMain.java
  core/src/main/java/io/questdb/cutlass/http/client/Response.java
  core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpErrorHandlingTest.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/http/MetricsIODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/http/SettingsEndpointTest.java
  core/src/test/java/io/questdb/test/cutlass/http/TestHttpClient.java
  core/src/test/java/io/questdb/test/cutlass/http/client/ChunkedResponseTest.java
  core/src/test/java/io/questdb/test/cutlass/http/client/ResponseTest.java
Labels: Tidy up, tandem

#4228 fix(sql): fix non-existing symbol bind variable initialization in indexed filter queries
  core/src/main/java/io/questdb/griffin/engine/table/DeferredSymbolIndexRowCursorFactory.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Labels: Bug, SQL

#4229 chore(core): remove basic auth realm from HTTP 401 (Unauthorized) responses
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
Labels: tandem

#4234 fix(sql): potential incorrect results in non-keyed parallel GROUP BY query
  core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByNotKeyedRecordCursor.java
  core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
Labels: Bug, SQL

#4237 test(core): fix edge case of snapshot restore failure when data copied under heavy ddl load
  core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java
Labels: Bug, Core

#4233 fix(sql): segfault when running SAMPLE BY query with index-based filter and last/first functions
  core/src/main/c/share/bitmap_index_utils.cpp
  core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java
  core/src/main/java/io/questdb/std/BitmapIndexUtilsNative.java
  core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
  core/src/main/resources/io/questdb/bin/linux/libasm.a
  core/src/main/resources/io/questdb/bin/windows/libquestdb.dll
  core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Labels: Bug, SQL

#4241 chore(core): fix path of todo file used during snapshot restore
  core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java
Labels: Bug, Core

#4249 chore(http): fix basic auth handling
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java
  core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java
  core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
Labels: REST API, tandem
