Repository questdb/questdb, pull requests merged in 2025-07, with the labels that each got.

#5807 chore(sql): error when extracting array values from large group by maps
  core/src/main/java/io/questdb/cairo/map/ShardedMapCursor.java
  core/src/test/java/io/questdb/test/cairo/ArrayTest.java
Labels: Bug, SQL

#5813 ci(pgwire): reduce unnecessary runs of R workflow
  .github/workflows/r_test.yml
Labels: CI

#5800 chore(sql): fix distinct SQL rewrite for array access operators
  core/src/main/java/io/questdb/cairo/arr/ArrayTypeDriver.java
  core/src/main/java/io/questdb/cairo/arr/BorrowedFlatArrayView.java
  core/src/main/java/io/questdb/cairo/arr/FlatArrayView.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/test/java/io/questdb/test/cairo/ArrayTest.java
Labels: Bug, SQL

#5904 feat(sql): kahan summation for `array_sum` and `array_cum_sum`
  core/src/main/java/io/questdb/cairo/arr/BorrowedFlatArrayView.java
  core/src/main/java/io/questdb/cairo/arr/FlatArrayView.java
  core/src/main/java/io/questdb/griffin/engine/functions/array/DoubleArrayCumSumFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/array/DoubleArraySumFunctionFactory.java
  core/src/test/java/io/questdb/test/cairo/ArrayTest.java
  core/src/test/java/io/questdb/test/cairo/fuzz/ParallelGroupByFuzzTest.java
Labels: SQL

#5896 feat(sql): ALTER MATERIALIZED VIEW SET REFRESH support
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/main/java/io/questdb/cairo/mv/MatViewDefinition.java
  core/src/main/java/io/questdb/cairo/mv/MatViewGraph.java
  core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java
  core/src/main/java/io/questdb/cairo/mv/MatViewState.java
  core/src/main/java/io/questdb/cairo/mv/MatViewStateStoreImpl.java
  core/src/main/java/io/questdb/cairo/mv/MatViewTimerJob.java
  core/src/main/java/io/questdb/cairo/wal/MetadataService.java
  core/src/main/java/io/questdb/cairo/wal/seq/MetadataServiceStub.java
  core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFromFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampFloorFromOffsetFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java
  core/src/main/java/io/questdb/griffin/engine/ops/AlterOperationBuilder.java
  core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/cairo/mv/MatViewGraphAndStateStoreTest.java
  core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
  pkg/ami/marketplace/assets/server.conf
Labels: New feature, SQL

#5958 fix(sql): exception when JIT compiling a filter like `WHERE symbol = ''''`
  core/src/main/java/io/questdb/griffin/engine/functions/constants/SymbolConstant.java
  core/src/test/java/io/questdb/test/griffin/CompiledFilterTest.java
Labels: Bug, SQL

#5934 chore(core): move context initialization out of connection-accepting thread
  core/src/main/java/io/questdb/PropServerConfiguration.java
  core/src/main/java/io/questdb/PropertyKey.java
  core/src/main/java/io/questdb/client/Sender.java
  core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/http/HttpMinServerConfigurationWrapper.java
  core/src/main/java/io/questdb/cutlass/http/HttpServerConfigurationWrapper.java
  core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
  core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiverConfigurationWrapper.java
  core/src/main/java/io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
  core/src/main/java/io/questdb/cutlass/pgwire/PGWireConfigurationWrapper.java
  core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java
  core/src/main/java/io/questdb/network/AbstractIODispatcher.java
  core/src/main/java/io/questdb/network/DefaultIODispatcherConfiguration.java
  core/src/main/java/io/questdb/network/IOContext.java
  core/src/main/java/io/questdb/network/IOContextFactory.java
  core/src/main/java/io/questdb/network/IOContextFactoryImpl.java
  core/src/main/java/io/questdb/network/IODispatcher.java
  core/src/main/java/io/questdb/network/IODispatcherConfiguration.java
  core/src/main/java/io/questdb/network/JavaTlsClientSocket.java
  core/src/main/java/io/questdb/network/PlainSocket.java
  core/src/main/java/io/questdb/network/Socket.java
  core/src/main/java/io/questdb/network/TlsSessionInitFailedException.java
  core/src/main/resources/io/questdb/site/conf/server.conf
  core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
  core/src/test/java/io/questdb/test/ServerMainTest.java
  core/src/test/java/io/questdb/test/cutlass/IODispatcherHeartbeatTest.java
  core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpContextTest.java
  core/src/test/java/io/questdb/test/cutlass/line/tcp/EllipticCurveAuthConnectionContextTest.java
  core/src/test/java/io/questdb/test/cutlass/pgwire/PGTlsCompatTest.java
  core/src/test/resources/server.conf
Labels: tandem

#5955 chore(core): switch ent to modern pg authenticator
  core/src/main/java/io/questdb/cutlass/pgwire/modern/CleartextPasswordPgWireAuthenticatorModern.java
  core/src/main/java/io/questdb/cutlass/pgwire/modern/DefaultPgWireAuthenticatorFactoryModern.java
Labels: tandem
