Repository questdb/questdb, pull requests merged in 2025-03, with the labels that each got.

#5431 fix(sql): missing null symbol value in query with not in symbol filter
  core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java
  core/src/test/java/io/questdb/test/cairo/TableReaderReloadTest.java
  core/src/test/java/io/questdb/test/griffin/ReaderReloadTest.java
  core/src/test/java/io/questdb/test/griffin/SymbolTest.java
Labels: Bug, SQL

#5450 fix(sql): fix memory leaks when parsing sub-queries in timestamp filter
  core/src/main/java/io/questdb/griffin/WhereClauseParser.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/eq/EqTimestampCursorFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/lt/GtTimestampCursorFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/lt/LtTimestampCursorFunctionFactoryTest.java
Labels: Bug, SQL

#5448 test(pgwire): bump asyncpg and psycopg2 clients for python 3.13 compatibility
  compat/src/test/php/runner.php
  compat/src/test/python/requirements_asyncpg_stable.txt
  compat/src/test/python/requirements_psycopg2_stable.txt
Labels: CI, Compatibility

#5452 test(sql): makes r2dbc test to use ipv4
  compat/src/test/java/io/questdb/compat/R2DBCTest.java
Labels: CI, Compatibility

#5404 test(pgwire): add nodejs test runner
  .github/workflows/pgwire_stable.yml
  compat/src/test/nodejs/package-lock.json
  compat/src/test/nodejs/package.json
  compat/src/test/nodejs/runner.js
  compat/src/test/resources/test_cases.yaml
  compat/src/test/scenarios_stable.sh
  core/src/main/java/io/questdb/cutlass/pgwire/PGOids.java
Labels: Postgres Wire, Compatibility

#5446 fix(core): fix update table busy error when table is created concurrently with update query
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: Bug, Core

#5480 fix(sql): Function args in `GreatestNumericFunction` and `LeastNumericFunction` should be deep-cloned
  core/src/main/java/io/questdb/griffin/engine/functions/math/GreatestNumericFunctionFactory.java
  core/src/main/java/io/questdb/griffin/engine/functions/math/LeastNumericFunctionFactory.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/finance/GreatestNumericFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/functions/finance/LeastNumericFunctionFactoryTest.java
  core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
Labels: Bug, SQL

#5474 chore(core): refactoring for explain create table/mat view ent fixes
  core/src/main/java/io/questdb/cairo/CairoEngine.java
  core/src/main/java/io/questdb/griffin/SqlParserCallback.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationBuilderImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationBuilderImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationImpl.java
  core/src/test/java/io/questdb/test/cairo/mv/CreateMatViewTest.java
Labels: tandem

#5494 test(pgwire): fix racy test with thread-local memory leak
  core/src/test/java/io/questdb/test/cutlass/pgwire/PreparedStatementInvalidationTest.java
Labels: Bug, Java, Flaky Test

#5509 chore(core): fix relatively persistent fuzz test failure
  core/src/main/java/io/questdb/cairo/CairoException.java
  core/src/main/java/io/questdb/cairo/TableWriter.java
  core/src/test/java/io/questdb/test/cairo/fuzz/FuzzRunner.java
Labels: Flaky Test

#5505 chore(sql): consistently remove 'public.' prefix
  core/src/main/java/io/questdb/griffin/SqlKeywords.java
  core/src/main/java/io/questdb/griffin/SqlOptimiser.java
  core/src/main/java/io/questdb/griffin/SqlParser.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationBuilderImpl.java
  core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationImpl.java
  core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Labels: SQL

#5527 fix(sql): crash when GROUP BY key includes timestamp
  core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java
  core/src/test/java/io/questdb/test/griffin/GroupByTest.java
Labels: Bug, SQL

#5529 perf(sql): speed-up of simple projections
  core/src/main/java/io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java
Labels: SQL, Performance
